.travis.yml
Gemfile

Just enough changes to keep the Travis-CI build from failing at us while we work towards enabling rubocop.

Get basic Travis-CI up and running. No Rubocop yet

---

metadata.json

This updates the metadata.json to match the format and whitespacing produced by the Puppet module packaging tool.
Thanks!

updates metadata.json to match output of Puppet Module Tool

---

CHANGELOG.md
README.md
docs/README-agent-install.md

We've changed the platform name used in the puppet agent packages from
nxos -> cisco-wrlinux to reflect that these packages may not be limited
to NX-OS in the future. All nxos named packages will be removed from
yum.puppetlabs.com shortly.

Update urls to Puppet Labs repo packages

---

.travis.yml

Travis is failing all builds due to beaker's dependency on fog-google.  fog-google 0.1.1 requires ruby version 2.0 minimum and Travis attempts to build with 1.9.
> Gem::InstallError: fog-google requires Ruby version >= 2.0.
> Installing specinfra 2.43.10
> An error occurred while installing fog-google (0.1.1), and Bundler cannot
> continue.
This is a quick fix for the puppet module to use the 2.1.6 rvm and resume passing the Travis build checks.  I am queueing up another pull request for cisco-network-node-utils that will require ruby version 2.1 or higher.  Puppet [appears to be in the process of deprecating ruby 1.9](https://docs.puppetlabs.com/guides/platforms.html#ruby-versions) so it would be best in the long run to upgrade to 2.1 now.

Upgrade rvm version to support dependencies

---

lib/puppet/provider/network_snmp/nxapi.rb
tests/beaker_tests/network_snmp/network_snmp-provider-defaults.rb
tests/beaker_tests/network_snmp/network_snmplib.rb

tests/beaker_tests/network_snmp/network_snmp-provider-defaults.rb passed in 17.47 seconds
Test Suite: tests @ 2015-10-08 13:57:25 +0100
Total Suite Time: 17.46 seconds
Average Test Time: 17.46 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1

Added NXOS provider for network_snmp

---

lib/puppet/provider/name_server/nxapi.rb
tests/beaker_tests/netdev_stdlib/name_server_provider_defaults.rb
tests/beaker_tests/netdev_stdlib/name_serverlib.rb

The puppetlabs-netdev_stdlib module has a name_server resource. This
commit adds a provider for this resource.
Requires cisco/cisco-network-node-utils#2

Add name_server provider

---

lib/puppet/provider/network_dns/nxapi.rb
tests/beaker_tests/netdev_stdlib/network_dns_provider_nondefaults.rb
tests/beaker_tests/netdev_stdlib/network_dnslib.rb

This adds the network_dns provider, which uses the node-utils apis for
DomainName, DnsDomain, and NameServer for it's various properties.

Add network_dns provider for netdev_stdlib

---

lib/puppet/provider/network_vlan/nxapi.rb
tests/beaker_tests/netdev_stdlib/network_vlan_provider_nondefaults.rb
tests/beaker_tests/netdev_stdlib/network_vlanlib.rb

```
tests/beaker_tests/netdev_stdlib/network_vlan_provider_nondefaults.rb passed in 72.26 seconds
Test Suite: tests @ 2015-10-21 13:59:25 -0700
Total Suite Time: 72.26 seconds
Average Test Time: 72.26 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
```
Closes #17

Update Network vlan PR with rubocop and beaker tests

---

lib/puppet/provider/radius/nxapi.rb
tests/beaker_tests/radius/radius_provider_defaults.rb
tests/beaker_tests/radius/radiuslib.rb

This is a dummy provider. That is, when a manifest has enable set to either true or false, the provider will come back as if the same value is already set.

Added dummy NXOS provider for radius

---

README.md
examples/demo_bgp.pp
lib/puppet/provider/cisco_bgp_af/nxapi.rb
lib/puppet/type/cisco_bgp.rb
lib/puppet/type/cisco_bgp_af.rb
tests/beaker_tests/bgpaf/test_bgpaf.rb
tests/beaker_tests/lib/utilitylib.rb

Summary:
1) Added `additional_paths*`, `dampening*`, `dampen_igp_metric` and `networks` properties.
2) Modification to beaker infra `tests/beaker_tests/lib/utilitylib.rb` to support array of arrays.
3) Update to `cisco_bgp.rb` to use `Cisco::RouterBgp.process_asnum` method
All beaker tests pass
Rubocop passes

New cisco_bgp_af properties

---

README.md
lib/puppet/type/cisco_bgp_af.rb
tests/beaker_tests/bgpaf/test_bgpaf.rb

It's not obvious from the diffs but there are no functional changes in this commit; I'm simply moving
the references into alpha order.
rubocop/beaker are clean

Alpha-order bgp_af properties

---

lib/facter/cisco.rb
lib/puppet/provider/cisco_command_config/cisco_os_shim.rb

Renamed provider from nxapi to cisco_os_shim.  Added XR symbol to provider and facter.
```
robgrie@puppetmaster:~/forks/robert-w-gries/cisco-network-puppet-module$ rubocop
Inspecting 152 files
........................................................................................................................................................
152 files inspected, no offenses detected
```
Note:  Facter errors because structured output is not supported in grpc yet.
```
[sunstone47:/harddisk:]$ puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Error: Facter: error while resolving custom fact "cisco": no implicit conversion of String into Integer
Info: Caching catalog for sunstone47.cisco.com
Info: Applying configuration version '1446134674'
Notice: …
```

Feature/grpc with cisco_command_config support

---

tests/beaker_tests/snmpserver/snmpserver_provider_defaults.rb
tests/beaker_tests/snmpserver/snmpserver_provider_negatives.rb
tests/beaker_tests/snmpserver/snmpserver_provider_nondefaults.rb
tests/beaker_tests/snmpserver/snmpserverlib.rb

snmpserver tests were validating defaults against an erroneous cli
Added a helper function to check each property's default cli string
rubocop is clean
```
beaker_tests/snmpserver:
Attempted: 4
Passed: 4
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 4
```

snmpserver beaker fixes

---

tests/beaker_tests/netdev_stdlib/name_server_provider_defaults.rb

% beaker --test beaker_tests/netdev_stdlib/name_server_provider_defaults.rb
Attempted: 1
Passed: 1
% rubocop beaker_tests/netdev_stdlib/name_server_provider_defaults.rb
Inspecting 1 file
.
1 file inspected, no offenses detected

Add exit codes for initial test setup call.

---

tests/beaker_tests/radius_server/radius_server_provider_defaults.rb

The test did not cleanup existing server before starting the test.
./radius_server_provider_defaults.rb passed in 30.94 seconds
Begin ./radius_serverlib.rb
./radius_serverlib.rb passed in 0.05 seconds
Test Suite: tests @ 2015-11-04 04:01:44 -0500
Total Suite Time: 30.99 seconds
Average Test Time: 15.50 seconds
Attempted: 2
Passed: 2
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 2

Added cleanup logic to radius_server beaker tests

---

examples/demo_all.pp
examples/demo_domain.pp
examples/demo_ntp.pp
examples/demo_radius.pp
examples/demo_syslog.pp
tests/beaker_tests/netdev_stdlib/network_dns_provider_nondefaults.rb

1) All new cisco providers for netdev types added.
2) Fixed beaker test issues.
```
root@dt-n9k5-1#puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for dt-n9k5-1.cisco.com
Info: Applying configuration version '1446691554'
Notice: /Stage[main]/Ciscopuppet::Demo_bgp/Cisco_bgp[55.77 blue]/ensure: created
Notice: /Stage[main]/Ciscopuppet::Demo_bgp/Cisco_bgp_af[55.77 blue ipv4 unicast]/ensure: created
Notice: /Stage[main]/Ciscopuppet::Demo_bgp/Cisco_bgp_af[55.77 blue ipv6 unicast]/ensure: created
Notice: /Stage[main]/Ciscopuppet::Demo_bgp/Cisco_bgp_neighbor[55.77 blue 1.1.1.1]/ensure: created
Notice: /Stage[main]/Ciscopuppet::Demo_bgp/Cisco_bgp_neighbor[55.77 blue 2.2.2.2]/ensure: created
Notice: …
```

Add netdev providers to demo manifest

---

tests/beaker_tests/snmpserver/snmpserver_provider_defaults.rb
tests/beaker_tests/snmpserver/snmpserver_provider_nondefaults.rb
tests/beaker_tests/snmpserver/snmpserverlib.rb

Begin ./snmpserverlib.rb
./snmpserverlib.rb passed in 0.01 seconds
Test Suite: tests @ 2015-11-05 07:15:33 -0500
Total Suite Time: 86.49 seconds
Average Test Time: 21.62 seconds
Attempted: 4
Passed: 4
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 4

Beaker snmpserver fix

---

examples/demo_bgp_ipv4.pp
examples/demo_roles_site.pp
lib/puppet/type/cisco_interface.rb

1) Comment to clarify that bgp command config password is not idempotent. (expected)
2) Namespace fix for roles based demo manifest.
3) Fixed property switchport_trunk_allowed_vlan idempotence issue.

Demo manifest bug fixes

---

examples/demo_aaa.pp
examples/demo_all.pp
lib/puppet/provider/cisco_aaa_group_tacacs/nxapi.rb
lib/puppet/type/cisco_aaa_group_tacacs.rb
tests/beaker_tests/aaagrouptacacs/aaagroup_provider_defaults.rb
tests/beaker_tests/aaagrouptacacs/aaagroup_provider_negatives.rb
tests/beaker_tests/aaagrouptacacs/aaagroup_provider_nondefaults.rb
tests/beaker_tests/aaagrouptacacs/aaagrouplib.rb

Beaker tests pass, manifest runs, no rubocop complaints for ruby 2.2, etc. I'll update docs in an update commit.
I used the older beaker test layout because I based my tests off of snmp_community. I can rewrite them if necessary, but I will be sad.

puppet type, provider, beaker tests, manifest for aaa_group_tacacs

---

lib/puppet/type/cisco_bgp.rb
lib/puppet/type/cisco_bgp_af.rb
lib/puppet/type/cisco_bgp_neighbor.rb
lib/puppet/type/cisco_bgp_neighbor_af.rb
lib/puppet_x/cisco/cmnutils.rb

BGP types were generating error because they were attempting to use cisco_node_utils gem methods before the gem was installed.  This fixes that problem.
1) Beaker Tests Pass
```
bgp/test_bgp_title_patterns.rb passed in 214.69 seconds
Test Suite: tests @ 2015-11-10 02:46:39 -0500
Total Suite Time: 367.25 seconds
Average Test Time: 91.81 seconds
Attempted: 4
Passed: 4
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 4
```
2) Demo Manifest Works
```
root@agent-lab10-nx#puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for agent-lab10-nx.cisco.com …
```

Fixed bgp type processing errors

---

examples/demo_interface.pp
lib/puppet/provider/cisco_interface/nxapi.rb
lib/puppet/type/cisco_interface.rb

- Subset of demo_interface.pp for features supported on XR
- Recognize `MgmtEth` as equivalent to `mgmt`
```puppet
cisco_interface { 'gigabitethernet0/0/0/0':
ensure              => 'present',
ipv4_address        => '192.168.122.222',
ipv4_netmask_length => '24',
ipv4_proxy_arp      => 'false',
ipv4_redirects      => 'false',
mtu                 => '1514',
shutdown            => 'false',
}
cisco_interface { 'gigabitethernet0/0/0/1':
ensure              => 'present',
description         => 'managed by puppet',
ipv4_address        => '192.168.55.55',
ipv4_netmask_length => '24',
ipv4_proxy_arp      => 'false',
ipv4_redirects      => 'false',
mtu                 => '1600',
shutdown            => 'true',
vrf                 => 'test',
}
```

cisco_interface support for XR

---

docs/README-develop-beaker-scripts.md
tests/beaker_tests/lib/utilitylib.rb

Adds support for grpc_port parameter in hosts.cfg file and allows connection to grpc port on switch.

grpc_port parameter supported in hosts cfg file

---

lib/puppet/provider/cisco_bgp/nxapi.rb
lib/puppet/type/cisco_bgp.rb

I wasn't handling the default case at all (mea culpa). So added the puppet setter to override the default behavior.
Then I had a bug in the validate method (checking peers_array instead of 'value').
Then Chris sent out his simplified code for all this, applied that and everything, including the default case works well now.
Rubocop happy.
manual testing happy
Log of puppet agent and outcome below:
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/type/cisco_bgp.rb]/content: content changed '{md5}daee343152471f669d56379ce8010641' to '{md5}b5aa67d0e668a81bd04b1b41057d8cbb'
Info: Caching catalog for sunstone123.cisco.com
Info: Applying configuration version '1447953276'
Notice: /Stage[main]/Main/Node[default]/Cisco_bgp[default_vrf_global]/confederation_peers: …

Couple of confed peers fixes

---

examples/demo_aaa.pp
lib/puppet/provider/cisco_aaa_authentication_login/nxapi.rb
lib/puppet/type/cisco_aaa_authentication_login.rb
tests/beaker_tests/aaaauthelogin/aaaautheloginlib.rb
tests/beaker_tests/aaaauthelogin/test_aaaauthelogin_defaults.rb
tests/beaker_tests/aaaauthelogin/test_aaaauthelogin_negatives.rb
tests/beaker_tests/aaaauthelogin/test_aaaauthelogin_nondefaults.rb
tests/beaker_tests/lib/utilitylib.rb

AAA Authentication Login Type/Provider/Beaker tests
Tests pass, rubocop passes, etc.
I noticed there isn't a good way for beaker to detect errors/warnings in puppet runs, e.g. invalid title patterns. I modified test_manifest to enable this. Thoughts?
Edit: I'm not sure why my local rubocop disagrees with github, will update.

Authentication login

---

tests/beaker_tests/fileservicepkg/filesvcpkglib.rb
tests/beaker_tests/fileservicepkg/service_provider_nondefaults.rb

The following testcases pass for XR and Nexus:
```
fileservicepkg/file_provider_nondefaults.rb
fileservicepkg/service_provider_nondefaults.rb
fileservicepkg/package_provider_nondefaults_1.rb
```
Tested service is now `bootlogd` because `syslog` does not function on XR.

Beaker passes on XR for builtin service provider

---

CHANGELOG.md
README.md
examples/demo_vrf.pp
lib/puppet/provider/cisco_vrf/nxapi.rb
lib/puppet/type/cisco_vrf.rb
tests/beaker_tests/vrf/test_vrf_provider_nondefaults.rb
tests/beaker_tests/vrf/vrflib.rb

1. pass beaker test
Total Suite Time: 98.02 seconds
Average Test Time: 98.02 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
I found the non_default test the non_default value, default value. idempotence and title patten test.
So I add the vni as a property in corresponding place.
2. pass static analysis

add vni to cisco_vrf

---

README.md

1. VNI   = Virtual Network Idendifier instead of VXLAN Network Identifier
2. cisco_vni moved out of the VXLAN grouping as it is an independent object.

VNI updates

---

CHANGELOG.md
README.md
examples/demo_aaa.pp
lib/puppet/provider/cisco_aaa_authorization_login_exec_svc/nxapi.rb
lib/puppet/type/cisco_aaa_authorization_login_exec_svc.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/aaaloginexecsvclib.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_defaults.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_negative.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_nondefaults.rb

beaker passes, example manifest runs successfully, rubocop passes, etc. this is the same thing as the aaa login config service pull request that just got merged, with all the references to "cfg" changed to "exec". would love to get this committed before the holidays

aaa login exec svc

---

CHANGELOG.md
README.md
examples/demo_netdev_snmp.pp
lib/puppet/provider/snmp_notification/nxapi.rb
tests/beaker_tests/netdev_stdlib/snmp_notification_provider_defaults.rb
tests/beaker_tests/netdev_stdlib/snmp_notificationlib.rb

TestCase :: SNMP Resource :: All Attributes Defaults :: End
tests/beaker_tests/netdev_stdlib/snmp_notification_provider_defaults.rb passed in 32.57 seconds
Test Suite: tests @ 2015-12-10 11:31:50 +0000
Total Suite Time: 32.57 seconds
Average Test Time: 32.57 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
No tests to run for suite 'post_suite'
Cleanup: cleaning up after successful run
Warning: ssh connection to master has been terminated
Warning: ssh connection to n9kv1 has been terminated

adding snmp_notification

---

tests/beaker_tests/lib/utilitylib.rb

New set of simple beaker test lib api's to use `facter` to query for the cisco OS and cisco hardware information.  This is needed to branch test code based on the following.
* Cisco OS Example: `nexus` vs `xr`
* Cisco Hardware Information Example: `n3k`, `n9k`, `n7k` etc...
Note, beaker does have a built in `fact_on` method but I chose not to use this method primarily due to the fact that for custom cisco facts we have to prepend `sudo` to the command and the api does not allow this.
These api's are needed to unblock several teams that are writing test cases for the various platforms, however I am investigating methods to remove the hardcoded path to the `facter` binary (would be useful for `puppet` binary as well).  I would like to handle that in a subsequent PR.

Beaker test lib facter helper methods

---

lib/puppet/parser/functions/platform_get.rb

New puppet module custom function that can be called from a manifest to distinguish between platforms using the cisco custom fact `cisco.hardware.type`.  Currently supports various Nexus platforms but can be extended when needed.
Custom Functions Doc: https://docs.puppetlabs.com/guides/custom_functions.html
NOTE: For NX-OSv the function currently returns 'n9k' but if the team feels like 'nxv'  or something along those lines would be better choice I can make the change.
The function can be called in the manifest like this: `$foo = platform_get()`

platform_get module function

---

README.md

Puppet forge does not handle links to nested readme files. I have made them link directly to the github pages.

updating links for other READMEs to github urls

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_interface/nxapi.rb
lib/puppet/provider/cisco_interface_channel_group/nxapi.rb
lib/puppet/type/cisco_interface.rb
lib/puppet/type/cisco_interface_channel_group.rb
tests/beaker_tests/cisco_interface/routedintf_provider_negatives.rb
tests/beaker_tests/cisco_interface/routedintf_provider_nondefaults.rb
tests/beaker_tests/cisco_interface/routedintflib.rb
tests/beaker_tests/cisco_interface_channel_group/test_interface_channel_group.rb
tests/beaker_tests/lib/utilitylib.rb

- moved channel_group property out of interface provider, into new interface_channel_group provider
- channel-group causes problems in nxos when it is present on an interface; e.g. you cannot change switchport modes, etc
- moving it into its own provider allows the manifest to explicitly remove it while allowing new (non-channel-group) properties to be added to the interface

Initial commit interface_channel_group provider

---

tests/beaker_tests/cisco_interface_ospf/ospfintf_provider_defaults.rb
tests/beaker_tests/cisco_interface_ospf/ospfintf_provider_negatives.rb
tests/beaker_tests/cisco_interface_ospf/ospfintf_provider_nondefaults.rb
tests/beaker_tests/cisco_interface_ospf/ospfintflib.rb
tests/beaker_tests/lib/utilitylib.rb

Fixes to `cisco_interface_ospf` beaker tests that enable them to run across all Nexus platforms.
- Removed `vsh` commands used to validate configuration commands.
- New utilitylib method to return existing slot and port information for existing line card modules.  Allows us to avoide hard coding interfaces.
- Tests are skipped if no suitable line card is found.
Beaker tests run and pass on `n6|7|9k`

cisco_interface_ospf beaker fixes (all Nexus platforms)

---

tests/beaker_tests/cisco_interface/test_vlan_mapping.rb
tests/beaker_tests/cisco_interface_service_vni/test_interface_service_vni.rb
tests/beaker_tests/cisco_vdc/test_vdc.rb
tests/beaker_tests/lib/utilitylib.rb

This started off as a fix for bridge-domain but morphed into additional cleanups.
1. bridge-domain setup will fail if there's currently a bridge-domain config present on the testbed; so I had to check the current state and clean it up before adding the domain for the test.
2. This led to creating a specific config_bridge_domain helper method, which led to similar helper methods for the other mt_full_env setups. This area could probably still use some work but my commit gets it closer.

Tighten up testbed setups for vdc, vlan_mapping, service_vni

---

examples/demo_interface.pp

* Create acl dependencies before setting `ip_acl` properties
* Removed `speed` and `duplex` from demo manifest due to too many differences between platforms and linecards
* Use different interfaces for `channel_group` and `switchport mode access` testing
* 3k - passes
* 5k - **Needs testing**
* 6k - **Needs testing**
* 7k - passes
* 9k - passes

Demo Interface manifest fixes

---

docs/README-develop-beaker-scripts.md
tests/beaker_tests/lib/utilitylib.rb

Update the workflow in the Beaker readme to explain setting up TPNNS SSHd and non-root login on XR. Update utilitylib to use the SSH user/password from hosts.cfg instead of hard-coding 'root/lab'.

Use TPNNS SSHd. Don't hard-code user/pass in utilitylib.

---

CHANGELOG.md
README.md
examples/demo_netdev_port_channel.pp
lib/puppet/provider/port_channel/nxapi.rb
tests/beaker_tests/netdev_stdlib/port_channel_provider_defaults.rb

tests/beaker_tests/netdev_stdlib/port_channel_provider_defaults.rb passed in 101.50 seconds
Test Suite: tests @ 2016-01-29 14:58:44 +0000
Total Suite Time: 101.50 seconds
Average Test Time: 101.50 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1

adding port_channel from puppetlabs netdev_stdlib

---

examples/cisco/demo_interface.pp
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_defaults.rb
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_negatives.rb
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_nondefaults.rb
tests/beaker_tests/cisco_interface/test_interface.rb

Several updates here.
- Skip svi_autostate test in demo_manifest and beaker tests on `n(5|6)k` platforms. Not supported.
- Skip `tests/beaker_tests/cisco_aaa_group_tacacs` on `n(5|6|7)k` platforms.  Not supported in `release_1.2.0`
- Added missing call to `sys_def_switchport_shutdown?` method inside the test_harness in the interface beaker tests.
**N6K Tests**
```
Beaker::Hypervisor, found some none boxes to create
No tests to run for suite 'pre_suite'
Begin cisco_interface/./test_interface.rb
TestCase :: Resource cisco_interface
------------------------------------------------------------
Section 1. (L3) Property Testing
Using interface: ethernet1/1
* TestStep :: system default switchport
no system default switchport
* TestStep :: Pre Clean:
* Pre Clean: Set 'ethernet1/1' to default …
```

beaker interface and aaa fixes

---

bin/git/hooks/hook_lib
bin/git/hooks/hooks-wrapper
bin/git/hooks/post-merge/update-hooks
bin/git/hooks/post-rewrite/update-hooks
bin/git/hooks/pre-commit/rubocop
bin/git/hooks/pre-commit/validate-diffs
bin/git/hooks/pre-push/rubocop
bin/git/update-hooks

Copying over some of the most useful git hooks from cisco-network-node-utils. Others can be ported over as needed.

Copy relevant git hooks from cisco-network-node-utils

---

tests/beaker_tests/cisco_vlan/accessvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/accessvlan_provider_negatives.rb
tests/beaker_tests/cisco_vlan/accessvlan_provider_nondefaults.rb
tests/beaker_tests/cisco_vlan/accessvlanlib.rb
tests/beaker_tests/cisco_vlan/vlan/extendedvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/vlan/extendedvlan_provider_negatives.rb
tests/beaker_tests/cisco_vlan/vlan/extendedvlan_provider_nondefaults.rb
tests/beaker_tests/cisco_vlan/vlan/standardvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/vlan/standardvlan_provider_negatives.rb
tests/beaker_tests/cisco_vlan/vlan/standardvlan_provider_nondefaults.rb

Beaker fixes for vlan beaker tests to run on all Nexus platforms.
- Adds dynamic interface lookup rather then using hard coded int names.
- Removes vsh command calls.
**Tests pass on n(5|7|9)k**
- There is one failure but it's a bug on the n5/6k.

vlan beaker fixes

---

tests/beaker_tests/cisco_acl/test_acl.rb

test_acl was failing because it was expecting `puppet resource cisco_acl` to report `fragments => ''` in the default-value tests, but `fragments` defaults to `nil` and not to `''`.
```
Begin tests/beaker_tests/cisco_acl/test_acl.rb
TestCase :: Resource cisco_acl
------------------------------------------------------------
Section 1. Default Property Testing
* 
--------
* TestStep :: Setup switch for cisco_acl provider test
* Setup switch for cisco_acl provider test Removing cisco_acl 'ipv4 beaker_1'
--------
1.1 Default Properties [ensure => present] [ensure => present]
* TestStep :: 1.1 Default Properties [ensure => present] [ensure => present] :: MANIFEST    
1.1 Default Properties [ensure => present] [ensure => present] :: MANIFEST     :: PASS
* TestStep :: 1.1 Default Properties …
```

Fix cisco_acl failure due to wrong expectations

---

lib/puppet/provider/cisco_vxlan_vtep_vni/nxapi.rb
tests/beaker_tests/cisco_vdc/test_vdc.rb
tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

Summary of fixes:
- Fixes issue where `vxlan_vtep_vni` resource created a new resource when the resource was already present on the device.
- Skip vdc beaker tests on unsupported platforms.
- Added `n9k` platform support key to `vxlan_vtep*` beaker tests.
**VXLAN TESTS 9K**
```
Begin ./cisco_vxlan_vtep/./test_vxlan_vtep.rb
TestCase :: Resource cisco_vxlan_vtep
------------------------------------------------------------
Section 1. Default Property Testing
* 
--------
* TestStep :: Setup switch for cisco_vxlan_vtep provider test
* TestStep :: 1.1 Default Properties [ensure => present] :: MANIFEST    
1.1 Default Properties [ensure => present] :: MANIFEST     :: PASS
* TestStep :: 1.1 Default Properties [ensure => present] :: RESOURCE    
1.1 Default Properties [ensure => present] :: …
```

vdc and vxlan fixes

---

tests/beaker_tests/lib/utilitylib.rb

* NXOSv and possibly other platforms return an empty string to `facter -p cisco.hardware.type`, but they do respond to `facter -p cisco` with all cisco facts.
* This fix just adds a secondary lookup if the first attempt fails

Add secondary, broader search to facter platform lookup

---

CHANGELOG.md
README.md
examples/cisco/demo_vxlan.pp
examples/demo_all_cisco.pp
lib/puppet/provider/cisco_interface/nxapi.rb
lib/puppet/type/cisco_interface.rb
tests/beaker_tests/cisco_interface/test_interface.rb
tests/beaker_tests/lib/utilitylib.rb

This is basically https://github.com/cisco/cisco-network-puppet-module/pull/188, authored by @smigopal with a few minor updates.
**TESTS**
- Tests run on both `I2` and `I3` versions
- Tests run with the following `feature fabric forwarding`(`I2` only) and (`nv overlay evpn`) enabled and disabled manually prior to starting the test.
```
Beaker::Hypervisor, found some none boxes to create
No tests to run for suite 'pre_suite'
Begin ./cisco_interface/./test_interface.rb
TestCase :: Resource cisco_interface
------------------------------------------------------------
Section 1. (L3) Property Testing
Using interface: ethernet1/1
* TestStep :: system default switchport
no system default switchport
* TestStep :: Pre Clean:
* Pre Clean: Set 'ethernet1/1' to default state
--------
1.1 (L3) Default …
```

Extend cisco_interface to include 'fabric_forwarding_anycast_gateway' property

---

metadata.json

- Update `cisco-network-puppet-module` version to `1.2.0`
- Update `puppetlabs/netdev_stdlib` version requirement to be `0.11.1`
- https://forge.puppetlabs.com/puppetlabs/netdev_stdlib
**Build Module**
```
Notice: Building /root/github/release120/cisco-network-puppet-module for release
Module built: /root/github/release120/cisco-network-puppet-module/pkg/puppetlabs-ciscopuppet-1.2.0.tar.gz
```
**Install Module**
```
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ puppetlabs-ciscopuppet (v1.2.0)
└── puppetlabs-netdev_stdlib (v0.11.0 -> v0.11.1) …
```

Update module version and netdev_stdlib dependency

---

docs/README-agent-install.md

Adds OAC install documentation.
Few things missing will be added in a subsequent update
- OAC download link for n5/6k.  Kokomo has not been officially released yet.
- OAC documentation (need link)

Add OAC install documentation

---

CHANGELOG.md
README.md
docs/README-agent-install.md
lib/puppet/provider/port_channel/nxapi.rb
tests/beaker_tests/cisco_vlan/accessvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/accessvlan_provider_nondefaults.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
tests/beaker_tests/file_service_package/package_provider_nondefaults_2.rb
tests/beaker_tests/netdev_stdlib/domain_name_provider_defaults.rb

- Fixed Cisco NetDev port_channel provider to use the correct cisco_node_utils object.
- Fixed beaker test setup and cleanup issues.
- Fixed incomplete documentation references for the open agent container (OAC)

Hotfix v1.2.1

---

CHANGELOG.md
metadata.json

The metadata was never updated for 1.2.1 but a tag was already made, so this PR bumps the metadata to 1.2.2 so that the package will build cleanly with the correct version.

Bump metadata for 1.2.2 release

---

manifests/install.pp

The install manifest is working with Puppet 4 only (type system usage).
Puppet 4 AIO packages (like the one which will be installed on Cisco
devices) must use the 'puppet_gem' provider instead of the system 'gem'
provider.

Use correct provider

---

README.md
tests/beaker_tests/cisco_acl/test_ace.rb

Convert test_ace to new beaker format
* Tested on N9k, N7k, N5k
* N5k provider needs some work to handle 0001:0001::0001/128 ipv6 addr format; Mike already has some code to handle this so I've left a TBD in the test to follow up

Convert test_ace to new beaker format

---

CHANGELOG.md
README.md
examples/cisco/demo_vrf.pp
lib/puppet/provider/cisco_vrf_af/cisco.rb
lib/puppet/type/cisco_vrf_af.rb
tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb

Adding route_policy_export, route_policy_import, route_target_export_stitching, route_target_import_stitching.
All beaker tests passed on eXR and N9kv.

TA88175: cisco_vrf_af:pt:Add new puppet type for cisco_vrf_af for Nexus and XR

---

tests/beaker_tests/lib/utilitylib.rb

The extra_config arg wasn't actually being used anywhere, so I just removed it.  It would be nice in the future to be able to specify a tests hash key with static dependency config (at the root and test level), but it's not needed for now.

Put test_harness_dependencies back and remove extra_config arg.

---

tests/beaker_tests/cisco_stp_global/test_stp_global.rb

Chris asked me to remove the setup_sys_bd_stp() method and use the test_harness_dependencies for the beaker tests. This PR is for that.
All the test results were pass as before.

remove setup and add test_harness_dependencies

---

README.md
tests/beaker_tests/netdev_stdlib/network_dns_provider_nondefaults.rb

```
tests/beaker_tests/netdev_stdlib/network_dns_provider_nondefaults.rb passed in 119.37 seconds
Test Suite: tests @ 2016-03-14 15:43:05 +0000
Total Suite Time: 119.37 seconds
Average Test Time: 119.37 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
No tests to run for suite 'post_suite'
Cleanup: cleaning up after successful run
```

Updated test and README to support network_dns on ios_xr

---

README.md
docs/README-agent-install.md
docs/README-beaker-agent-install.md
docs/README-develop-beaker-scripts.md
docs/README-gem-install.md

* Add setup/installation examples for IOS XR
* Move information about installing/configuring cisco_node_utils gem into a new README-gem-install.md document so that this information can be easily referenced from several of the other READMEs without duplication.
* Various other attempts at reducing the duplication of information amongst multiple documents.

Documentation updates for IOS XR

---

CHANGELOG.md
examples/cisco/demo_interface.pp
lib/puppet/type/cisco_interface.rb
tests/beaker_tests/cisco_interface/test_interface.rb

This change modifies the type file of cisco_interface for the the property switchport_trunk_allowed_vlan to accept an arbitary range strings with the use of range_summarize(). The utility method range_summarize() massages the input resource string to a form that is compatible with the range summarization that is done by NxOS CLI on VLAN ranges. This takes care of idempotency issues.

modify switchport_trunk_allowed_vlan to use range_summarize()

---

tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
tests/beaker_tests/lib/utilitylib.rb

* similar to minitest check which skips all tests if platform is excluded
* Initially used with vxlan providers
Test with n3k:
```
-----
Begin beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
TestCase :: Resource cisco_vxlan_vtep_vni
Found Platform string: 'Nexus 3048 Chassis', Alias to: 'n3k'
TestCase ::
######################################################################
Skipping all tests; 'cisco_vxlan_vtep_vni' is unsupported on this node
######################################################################
:: SKIP
Begin teardown
End teardown
Warning: beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb skipped in 11.40 seconds
Test Suite: tests @ 2016-04-01 12:43:45 -0400
Total Suite Time: 11.40 …
```

Add skip_unless_supported() for beaker tests

---

tests/beaker_tests/cisco_bgp/test_bgp.rb
tests/beaker_tests/cisco_bgp_af/test_bgpaf.rb
tests/beaker_tests/cisco_bgp_neighbor/test_bgpneighbor.rb

* bgp: reconnect_interval was missing from test
* bgp_af: change redist expected value to sorted
* bgp_neighbor: add log_neighbor_changes

bgp: beaker platform fixes #1

---

tests/beaker_tests/cisco_bgp_neighbor_af/test_bgpneighboraf.rb

* The 'always' keyword on soft-reconfig is only supported on certain NX platforms
* I considered adding platform checks for it but decided instead to just remove it altogether since beaker is already testing soft-reconfig with other values and minitest does the full range of possible values.
* Also found that soft-reconfig is not supported at all on n8/9k when l2vpn is used

beaker: bgpneighboraf: soft-reconfig

---

examples/cisco/demo_acl.pp
lib/puppet/parser/functions/platform_get.rb
tests/beaker_tests/cisco_acl/test_ace.rb
tests/beaker_tests/lib/utilitylib.rb

Fixes the following:
- Adds platform checks where needed for the demo manifest.
- Adds n8kv support to platform_get() module function.
- Enable ace test for n8k
Beaker/Demo Manifest Pass on: n3k, n9k (I2 I3), n5k, n9k
n7k not run due to license issue
n6k not run due to availability of testbed.

ace demo manifest fixes

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_vtp/cisco.rb
lib/puppet/type/cisco_vtp.rb

**Summary of changes:**
- Updated docs to indicate support on n5k, n6k and n7k.
- Append `bootflash:/` to vtp filename if now mount is specified.
Tested on: n3k, n7k, n8k, n9k(I2 & I3).  Waiting on n5|6k to become available.
Note, all tests pass except an idempotence issue for vtp password.  This is a platform issue and the work around will be in a separate PR.

cisco_vtp fixes.

---

README.md
examples/cisco/demo_itd.pp
examples/cisco/demo_stp_vlan.pp
lib/puppet/provider/cisco_snmp_community/cisco.rb
tests/beaker_tests/cisco_stp_global/test_stp_global.rb

These are changes for 3 providers.
1, fcoe attribute in stp_global is not supported on n3k and so it is removed from demo manifest and beaker tests.
2. itd is supported only on n9k and n7k. Added exclude clause in the demo manifest so that the manifest will not throw errors for other nexus switches.
3. snmp_commity provider has an error where if there is a comminuty already existing on the switch, the beaker test is failing when it is trying to remove (because it is accessing group parameter after the community resource is removed). This is fixed.

Fix things for itd, stp, snmp_comm

---

README.md
examples/cisco/demo_portchannel.pp
lib/puppet/provider/cisco_portchannel_global/cisco.rb
tests/beaker_tests/cisco_portchannel_global/test_portchannel_global.rb

This is mainly portchannel_global provider support for n8k. Mike has the complete context of this, it is better if he reviews this. All tests are run on all switches and they all pass (including demo manifests)
1. There are lot of mistakes in the README.md file for this provider and they are corrected.
2. portchannel_global n8k support is added to demo manifest and the actual provider code is added and this utilizes the load_balance_type param from NU (the PR for that is already opened).
3. For n5k, the defaults are different from n6k (in fact they are very different within n5k flavors themsevles) which is causing some issues in the beaker tests. That is corrected.
Please check the comment put by Chris long back in the NU.
https://github.com/cisco/cisco-network-node-utils/blob/develop/lib/ …

pc for n8k

---

README.md

Currently we use a :x:  to indicate both `Unsupported` and `Not Applicable`.  I have updated the table to use a :heavy_minus_sign: to indicate `Not Applicable`.  I thought this looked a little better and reduces the amount of :x:'s.
For quick and easy viewing click here: https://github.com/cisco/cisco-network-puppet-module/blob/rel/readme_table_updates/README.md#cisco-providers

Update support table to indicate "Not Applicable"

---

README.md

Changed README.md file to add support for network_snmp, ntp_config, ntp_server, search_domain, syslog_server and syslog_settings.
There are no changes to any code and all tests (mintest, beaker and demo manifests) on all nexus platforms have passed.

README file changes for netdev provider support

---

README.md
examples/cisco/demo_encapsulation.pp
examples/cisco/demo_interface_service_vni.pp
lib/puppet/type/cisco_encapsulation.rb
tests/beaker_tests/cisco_encapsulation/test_encapsulation.rb
tests/beaker_tests/cisco_interface_service_vni/test_interface_service_vni.rb

* Fixes for interface_service_vni and encapsulation
* Add 'default' support to encapsulation and fixed idempotence issues
* Add pre-reqs and skips to demo manifests and beaker tests
* Reformatted beaker tests to use latest syntax
* Tested on n7k, all other platforms are skipped

test_interface_service_vni: platform cleanups

---

CHANGELOG.md
README.md
examples/demo_all_netdev.pp
examples/netdev/demo_network_vlan.pp
tests/beaker_tests/netdev_stdlib/network_vlan_provider_nondefaults.rb

- Doc Updates
- Removal of vsh commands in beaker tests.
**Beaker/Manifest Tests Pass On:** n3k, n5k, n6k, n7k, n8k, n9k (I2 and I3)

netdev vlan fixes

---

CHANGELOG.md
README.md
lib/puppet/provider/snmp_notification/cisco.rb
tests/beaker_tests/netdev_stdlib/snmp_notification_provider_defaults.rb

This PR is mainly for snmp netdev and port_channel netdev provider support for n5/6/7k.
1. Changed CHANGELOG.md file (including the changes which were not made for the other providers owned by me).
2. README.md file changes for the n5/6/7k support.
3. snmp_notification provider code changed because of idempotent issue (Thanks a lot Mike for your help!)
4. get_vshell_cmd for show cmd is replaced with puppet resource in the snmp_notification beaker tests because the show commands with piping (for ex: "sh run snmp all | include \"snmp-server enable traps\"") do not work on OAC as the dohost cmd on the OAC simply returns no data for them.

Snmp netdev provider support

---

lib/puppet/provider/cisco_interface_capabilities/cisco.rb
lib/puppet/type/cisco_interface_capabilities.rb
tests/beaker_tests/cisco_interface/test_interface_capabilities.rb
tests/beaker_tests/lib/utilitylib.rb

* New Type, Provider, and beaker utility; for use with interface testing.
* Tested mainly on n7k.
* Considered using facter for this but the overhead in processing time was more than desired and I didn't want to penalize every single puppet run; therefore it made more sense to make this an on-demand utility since it's only going to be used by beaker.
* Manual test:
```
cap = interface_capabilities(agent, 'ethernet9/1')
puts 'Speed: ' + cap['Speed']
puts 'Duplex: ' + cap['Duplex']
```
Result:
```
Speed: 10000,40000
Duplex: full
```

Add interface_capabilities helper

---

CHANGELOG.md
README.md
examples/netdev/demo_tacacs.pp
tests/beaker_tests/tacacs/tacacs_provider_defaults.rb
tests/beaker_tests/tacacs_global/tacacs_global_provider_defaults.rb
tests/beaker_tests/tacacs_server/tacacs_server_provider_defaults.rb
tests/beaker_tests/tacacs_server_group/tacacs_server_group_provider_defaults.rb

**Summary:**
- Updated docs for `tacacs_server` and `tacacs_server_group`
- Fixed manifest
- Added cleanup steps for beaker tests.
- Note, `tacacs` and `tacacs_global` are not ensurable so the cleanup step differs a bit.
Tests Pass On: n3k, n5k, n6k, n7k, n8k, n9k (I2 and I3)

netdev tacacs fixes

---

CHANGELOG.md
README.md
examples/cisco/demo_portchannel.pp
lib/puppet/provider/cisco_portchannel_global/cisco.rb
tests/beaker_tests/cisco_portchannel_global/test_portchannel_global.rb

This PR is for adding support of portchannel_global provider to n3k natively.
1. Changed README.md and CHANGELOG.md to reflect this.
2. demo manifest is changed to remove any discrepancies.
3. beaker tests are fixed for n3k to run separately from n9k since the CLIs are different now.

portchannel_global support for n3k native

---

tests/beaker_tests/cisco_interface_channel_group/test_interface_channel_group.rb

This PR is for beaker tests for interface_channel_group provider.
The hard coding of interface ethernet1/1 is removed by getting the intf dynamically using find_interface method.

interface_channel_group

---

tests/beaker_tests/cisco_vlan/vlan/extendedvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/vlan/extendedvlan_provider_nondefaults.rb
tests/beaker_tests/cisco_vlan/vlan/standardvlan_provider_defaults.rb
tests/beaker_tests/cisco_vlan/vlan/standardvlan_provider_nondefaults.rb

This PR is for removing bridge domains if they exist so that vlan tests pass.

cisco_vlan beaker fix

---

tests/beaker_tests/cisco_evpn_vni/test_evpn_vni.rb
tests/beaker_tests/cisco_itd_device_group/test_itd_device_group.rb
tests/beaker_tests/cisco_itd_device_group_node/test_itd_device_group_node.rb
tests/beaker_tests/cisco_itd_service/test_itd_service.rb
tests/beaker_tests/lib/utilitylib.rb

* On i2 images, `route-target both 2:2` does not nvgen and instead nvgens two entrie: `route-target import 2:2 ; route-target export 2:2`
* On i3 images, `route-target both 2:2` nvgens as entered, import/export do not and are treated as separate entities
* Added nexus_i2_image method (named this way to match the minitest method of the same name); renamed skip_nexus_i2_img to reflect new method
* Tested on N9-i2, N9-i3 (all affected beaker tests)

test_evpn_vni: add checks for i2_image

---

tests/beaker_tests/cisco_vdc/test_vdc.rb
tests/beaker_tests/lib/utilitylib.rb

fixing the parameters of the limit_resources_module_type() utility and fix the NU call with the 'default' arg

fix VDC beaker test failures

---

tests/beaker_tests/cisco_interface/test_interface_stp.rb

This PR is for cleaning up bridge domains if they exist so that vlan tests can pass.
Tested on n7k/n9k/n3k. brdige domains are only available on n7k, on all other nexus platforms, the added line of code is nop.

bd remove for interface stp vlan

---

README.md
tests/beaker_tests/cisco_evpn_vni/test_evpn_vni.rb

* Problem: route_target_both intermittently nvgens as import & export instead of 'both'.
* I was unable to find a trigger for what makes 'both' nvgen or not but it's clearly a bug in the cli (this issue exhibits on all platform types). I found that running the original test (which includes route_target_both) will pass fine one time then fail on another attempt. On failure I then try manually entering 'both' -- it nvgens import/export instead. When the test passes I try manual commands and they nvgen 'both' just fine. After discussing with Mike we concluded to just add a caveat to the readme:
* "The `route_target_both` property is discouraged due to the inconsistent behavior of the property across Nexus platforms and image versions. The 'both' keyword has a transformative behavior on some …

test_evpn_vni: route_target_both issues

---

tests/beaker_tests/file_service_package/service_provider_nondefaults.rb

The file_service_package/service_provider_nondefaults.rb is not apllicable to OAC platforms n5/6/7k. This PR is to skip the test on these platforms.
Tested on n6k, n7k (it skips) and n9k (it runs normally). Have not tested on n5k because of resource unavailability but the added code should skip on n5k also as it is just a string comparison.

skip file_service test for OAC

---

tests/beaker_tests/cisco_vrf/test_vrf.rb

test_vrf: skip rd test when i2 img

---

README.md
examples/cisco/demo_vxlan.pp
examples/demo_all_cisco.pp
lib/puppet/type/cisco_vxlan_vtep_vni.rb
tests/beaker_tests/cisco_overlay_global/test_overlay_global.rb
tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

- Included support for all nexus platforms (excluding 3k)
- Hold down time, ingress replication, peer list specific to 8,9k.
- added suppress_uuc - specific to 5,6k.
- changes in beaker tests accordingly.
- Manifest - ensure f3 vdc for 7k. Vxlan included in demo_all.

Vxlan Puppet changes for release 1.3

---

tests/beaker_tests/cisco_fabricpath_global/test_fabricpath_global.rb
tests/beaker_tests/cisco_fabricpath_topology/test_fabricpath_topology.rb
tests/beaker_tests/cisco_interface/test_vlan_mapping.rb
tests/beaker_tests/cisco_interface_service_vni/test_interface_service_vni.rb
tests/beaker_tests/lib/utilitylib.rb

* Mostly F3 & vlan related
* The F3 issue still needs work but we will address post-release.
* feature vni can only work if limit-resource module-type is set exclusively to 'f3'
* Tested (on N7k w/F3 module) all of the tests that use the methods I changed

N7k testbed cleanup fixes

---

CHANGELOG.md
README.md

* N8k and XR will not be officially supported in 1.3.0

Doc Chgs: Remove 8k, XR refs from README.md

---

tests/beaker_tests/cisco_stp_global/test_stp_global.rb
tests/beaker_tests/lib/utilitylib.rb

* test_stp_global cleanup was lacking
* Tested on n7,n9
```
--------
* TestStep :: Remove all vlans & bridge-domains
*
--------
* TestStep :: bridge domains
* bridge domains Removing cisco_bridge_domain '22'
* bridge domains Removing cisco_bridge_domain '24'
system bridge-domain none
*
--------
* TestStep :: vlans
* vlans Removing cisco_vlan '20'
* vlans Removing cisco_vlan '28'
```

Add bridge-domain cleanup to remove_all_vlans

---

examples/cisco/demo_interface.pp

```bash
Error: /Stage[main]/Ciscopuppet::Cisco::Demo_interface/Cisco_interface[Ethernet1/1]: Could not evaluate: [interface ethernet1/1] The command ' ip address 192.168.55.5/24 ' was rejected with error:
IP configuration not permitted on forwarding-enabled interfaces
```
```bash
Error: /Stage[main]/Ciscopuppet::Cisco::Demo_interface/Cisco_bridge_domain[100]: Could not evaluate: undefined method `split' for nil:NilClass
```

Platform check and fix misconfig

---

tests/beaker_tests/cisco_interface/test_interface_private_vlan.rb
tests/beaker_tests/lib/utilitylib.rb

* Found a bug on n9k where 'private-vlan association trunk' does not get cleaned up by 'default interface', which breaks this beaker test
* Created a workaround cleanup method that does 'no switchport'
* No support for private-vlan on 8k
* Tested on N9k-I3

test_interface_private_vlan: fix trunk assoc cleanup

---

lib/puppet/type/cisco_vlan.rb
lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/cisco_vlan/test_private_vlan.rb

This is the puppet counter-part to NU. The notes below are copied from: https://github.com/cisco/cisco-network-node-utils/pull/400
The main difference between these is a default check in Utils.normalize_range_array and that there's no Utils.dash_range_to_elements since that's not needed in puppet.
* The motivation for this change was finding yet another array normalizer in the private vlan code so these changes are initially meant to address fixes there. IMO our range summarize methods were getting a bit long and difficult to maintain; these new methods will hopefully simplify things somewhat.
* The main problem these methods are trying to solve is reconciling manifest inputs with getter results when there are overlapping ranges; e.g.:
* '2-5, 9, 4-6'     needs to be ['2-6', '9']
* ['2', …

normalize_range_array for puppet

---

CHANGELOG.md
README.md
examples/cisco/demo_vlan.pp
lib/puppet/provider/cisco_vlan/cisco.rb
lib/puppet/type/cisco_vlan.rb
tests/beaker_tests/cisco_vlan/test_private_vlan.rb

This PR is for refactoring private-vlan types in cisco_vlan provider. Only private_vlan_type and private_vlan_association are changed to pvlan_tupe and pvlan_association.
Tested on n3k, n6k, n7k, n8k and n9k. All demo_manifests and beaker tests passed.

cisco_vlan: pvlan refactor

---

CHANGELOG.md
README.md
examples/cisco/demo_interface.pp
lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/type/cisco_interface.rb
lib/puppet_x/cisco/autogen.rb
lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/cisco_interface/test_interface_private_vlan.rb
tests/beaker_tests/lib/utilitylib.rb

* Deprecated the private_vlan properties that were released with 1.3.0 and created new pvlan properties in their place.
* This is the companion to NU PR: cisco/cisco-network-node-utils#406
* Updated Type, Provider, Beaker, Demo, README, and CHANGELOG.
* Currently only tested on N7, N9-i3. Additional testing in prog.

cisco_interface: private_vlan refactor

---

lib/puppet/provider/package/cisco.rb

Add back the old regexp support so that the following is supported.
- Install package where name/title is the rpm file name.
- Install package where name/title is the 'short' package name (installed from local rpm repo)
- Install package where source rpm is specified and name/title is arbitrary or the short package name.
Tested on N9k.

Add back rpm filename regexp support

---

tests/beaker_tests/cisco_interface/interfacelib.rb
tests/beaker_tests/cisco_interface/test_interface_L2.rb
tests/beaker_tests/cisco_interface/test_interface_svi.rb

* test_interface_L2 should reset sys_def_switchport
* This test sets the system default switchport state to true but it should reset it to false when it's finished.
* Remove explicit anycast config
* anycast-gateway-mac is a required dependency; a recent commit added an explicit call to the test file to set this up; BUT we already had existing code for doing this that was part of interfacelib.rb
* The interfacelib code was returning early because of /unless/if/
* Tested on n9-i4

Misc test_interface fixes

---

CHANGELOG.md
README.md
examples/cisco/demo_bfd.pp
examples/demo_all_cisco.pp
lib/puppet/provider/cisco_bfd_global/cisco.rb
lib/puppet/type/cisco_bfd_global.rb
tests/beaker_tests/cisco_bfd_global/test_bfd_global.rb

This PR is for the cisco_bfd_global provider. 
All tests for demo_manifests and beaker pass across all platforms.
one property (interval) is not supported on n8k and n9k due to platform code issue. 
The changelog and README are updated except for n8k (which is missing globally).

cisco_bfd_global provider

---

README.md

* Moved Document Workflow Map to a Documentation Guide table at the end
* Combined Overview and Module Description
* Updated Usage section
* Moved info from the Limitations section into the Platform Support Matrix, which moved after the Resource Reference tables
* Created Example Manifests Section

README.md cleanup for 1.3.2

---

tests/beaker_tests/cisco_bridge_domain/test_bridge_domain.rb
tests/beaker_tests/cisco_bridge_domain/test_bridge_domain_vni.rb
tests/beaker_tests/cisco_vdc/test_vdc.rb
tests/beaker_tests/lib/utilitylib.rb

* Updated this test to work with non-F3 N7k testbeds.
* Initially set the VDC module-type to default state
* Then set module-type to F3 and test
* There's no great way to know which way to leave the module-type when this test completes, so:
* Reset module-type to default for non-F3 testbeds since leaving it as F3 means the device won't have any usable interfaces
* Noop for F3 testbeds so that it leaves their F3 still usable
* Tested on n6, n7-non-F3
Edit: Added some add'l fixes for bridge-domain tests

test_vdc: fix for non-F3 testbeds

---

lib/puppet/provider/cisco_vxlan_vtep_vni/cisco.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

The suppress_uuc property was never really added to puppet.  This adds the property and un-comments the associated test cases.
Tested on: n5k, n6k(skips), n8k, n9k(I2 and I3)

Fix vxlan_vtep_vni suppress_uuc prop

---

lib/puppet/provider/snmp_notification/cisco.rb
tests/beaker_tests/netdev_stdlib/snmp_notification_provider_defaults.rb
tests/beaker_tests/netdev_stdlib/snmp_notificationlib.rb

tests/beaker_tests/netdev_stdlib/snmp_notification_provider_defaults.rb passed in 64.67 seconds
Test Suite: tests @ 2016-05-31 15:24:59 +0100
Total Suite Time: 64.67 seconds
Average Test Time: 64.67 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
No tests to run for suite 'post_suite'
No tests to run for suite 'pre_cleanup'
Cleanup: cleaning up after successful run
Warning: ssh connection to master has been terminated
Warning: ssh connection to exr has been terminated

modifications for snmp_notification on IOS_XR

---

examples/netdev/demo_snmp.pp
lib/puppet/provider/snmp_user/cisco.rb
tests/beaker_tests/snmp_user/snmp_user_provider_defaults.rb
tests/beaker_tests/snmp_user/snmp_userlib.rb

This is to bring IOS XR support to snmp_user
This provider does not supported unencrypted passwords, thus all password specified must be already encrypted.
```
tests/beaker_tests/snmp_user/snmp_user_provider_defaults.rb passed in 234.26 seconds
Test Suite: tests @ 2016-06-14 18:04:38 +0100
Total Suite Time: 234.28 seconds
Average Test Time: 234.28 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
```

Added IOS XR support for snmp_user

---

lib/puppet/provider/cisco_command_config/cisco.rb

* Symptom: Simple cc manifest with a faulty line of config:
cisco_command_config { 'interface':
command  => '
interface loopback42
ipv6 pim foo
'
}
When puppet agent runs the cc provider drops into a rescue which should first print out the parts of the config that were successfully processed and then do a raise, but instead we see:
```
Error: undefined method 'previous' for #<Cisco::CliError:0x0000000460ac08>
```
* Analysis: `client.rb` was refactored a few months ago, wherein the `previous` hash key was renamed to `successful_input`. The cc providers (both puppet & chef) never got updated with the new key name.
* Ref: https://github.com/cisco/cisco-network-node-utils/blob/develop/lib/cisco_node_utils/client/nxapi/client.rb#L285
* Testing:
```
Linux# puppet agent -t --debug
...
Info: …
```

command_config: undefined method 'previous'

---

CHANGELOG.md
lib/puppet/provider/cisco_command_config/cisco.rb
lib/puppet/type/cisco_aaa_authorization_login_cfg_svc.rb
lib/puppet/type/cisco_aaa_authorization_login_exec_svc.rb
lib/puppet/type/cisco_interface.rb
lib/puppet/type/cisco_interface_ospf.rb
lib/puppet/type/cisco_snmp_community.rb
lib/puppet/type/cisco_snmp_user.rb
metadata.json

This update fixes the following issues:
- Remove autorequire references in cisco types.
- Fixes incompatibility between cisco resources and latest puppet agent rpm.
- Fix undefined method 'previous' bug in cisco_command_config provider.
Full beaker results using FCS dublin image:
```
Overall Stats
Passed     : 104
Passx      : 0
Failed     : 0
Aborted    : 0
Blocked    : 0
Skipped    : 15
Errored    : 3
TOTAL      : 122
Success Rate   : 97.54 %
```
The errored test cases are the following:
- DNS test case that is intentionally commented out.
- `test_private_vlan` passed on re-test.
- ./cisco_aaa_login_cfg_svc/test_aaalogincfgsvc_nondefaults.rb bug in dublin image.

Hotfix 1.3.2

---

tests/beaker_tests/cisco_snmp_server/snmpserver_provider_defaults.rb
tests/beaker_tests/cisco_snmp_server/snmpserver_provider_nondefaults.rb

The `cisco_snmp_server` tests were failing because they were still using vsh commands directly to test for property changes.  This update removes those commands since the changes are validated via the `puppet resource` command.
Test passes on n9k.  I did not test other platforms, but given the fact we are only removing vsh related steps the risk is low.

Remove vsh from cisco_snmp_server beaker tests

---

lib/puppet/provider/cisco_tacacs_server/cisco.rb
lib/puppet/type/cisco_aaa_authorization_login_exec_svc.rb
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_defaults.rb
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_negatives.rb
tests/beaker_tests/cisco_aaa_group_tacacs/aaagroup_provider_nondefaults.rb
tests/beaker_tests/cisco_aaa_login_cfg_svc/test_aaalogincfgsvc_defaults.rb
tests/beaker_tests/cisco_aaa_login_cfg_svc/test_aaalogincfgsvc_negative.rb
tests/beaker_tests/cisco_aaa_login_cfg_svc/test_aaalogincfgsvc_nondefaults.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_defaults.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_negative.rb
tests/beaker_tests/cisco_aaa_login_exec_svc/test_aaaloginexecsvc_nondefaults.rb

**Summary of changes:**
- Add cleanup methods that are called at the beginning and end of each test.
- Use of beaker DSL `teardown` method.
- Add back missing autorequires in `cisco_aaa_authorization_login_exec_svc.rb`
- Removed debug statement causing beaker tests to error.
Tested on: n9k and n5k.

Fix cisco_aaa* 'TACACS+ group delete denied, group is in use' issue

---

lib/puppet/type/cisco_bgp.rb
tests/beaker_tests/cisco_bgp/test_bgp.rb

Due to recent platform changes, the CLI for `event_history events
size disable` now results in the config `no event-history events`.
This change munges the manifest value of `false` to `size_disable`.
```bash
bash-4.2# /opt/puppetlabs/bin/puppet resource cisco_bgp '1 default' event_history_events='true'
cisco_bgp { '1 default':
ensure               => 'present',
event_history_events => 'size_small',
}
bash-4.2# /opt/puppetlabs/bin/puppet resource cisco_bgp '1 default' event_history_events='size_disable'
Notice: /Cisco_bgp[1 default]/event_history_events: event_history_events changed 'size_small' to 'size_disable'
cisco_bgp { '1 default':
ensure               => 'present',
event_history_events => 'size_small',
}
bash-4.2# /opt/puppetlabs/bin/puppet resource cisco_bgp '1 default' …
```

Munge events value 'false' to 'size_disable'

---

tests/beaker_tests/cisco_tacacs_server/tacacsserver_provider_defaults.rb
tests/beaker_tests/cisco_tacacs_server/tacacsserver_provider_negatives.rb
tests/beaker_tests/cisco_tacacs_server/tacacsserver_provider_nondefaults.rb
tests/beaker_tests/cisco_tacacs_server_host/tacacsserverhost_provider_defaults.rb
tests/beaker_tests/cisco_tacacs_server_host/tacacsserverhost_provider_negatives.rb
tests/beaker_tests/cisco_tacacs_server_host/tacacsserverhost_provider_nondefaults.rb

Calls to `get_vshell_cmd` are bad but they are especially bad inside of the guestshell.  They cause the tests to error out.
```
./cisco_tacacs_server/./tacacsserverlib.rb passed in 0.00 seconds
Test Suite: tests @ 2016-08-05 13:56:44 -0400
Total Suite Time: 127.12 seconds
Average Test Time: 31.78 seconds
Attempted: 4
Passed: 4
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 4
./cisco_tacacs_server_host/./tacacsserverhostlib.rb passed in 0.00 seconds
Test Suite: tests @ 2016-08-05 14:04:52 -0400
Total Suite Time: 158.92 seconds
Average Test Time: 39.73 seconds
Attempted: 4
Passed: 4
Failed: 0
Errored: 0
Skipped: 0 …
```

Remove get_vshell_cmd calls for cisco_tacacs_server* providers

---

tests/beaker_tests/network_snmp/network_snmp_provider_defaults.rb

The addition of `xr` support to the netdev `network_snmp` beaker tests introduced the defect.  The call to the `operating_system` api inside the `on ... do` block resulted in the `stdout` buffer being overwritten with the os info instead of the output from the `puppet resource` command.
This fix moves the call outside of the `on ... do`  and further streamlines the code.
Issue:
```
n9k-108.cisco.com executed in 0.18 seconds
MGW: stdout: nexus
MGW: output: nexus
MGW: pattern: (?-mix:enable +=> +'?false'?)
Warning: 
TestStep :: Match (?-mix:enable +=> +'?false'?) :: FAIL
```
With fix in place:
```
n9k-108.cisco.com 11:14:09$ source /etc/profile; sudo sh -c " ip netns exec management /opt/puppetlabs/bin/puppet resource network_snmp default "
network_snmp { 'default':
contact  => 'unset', …
```

Fix beaker test bug in network_snmp

---

examples/netdev/demo_snmp.pp
lib/puppet/provider/snmp_user/cisco.rb
tests/beaker_tests/snmp_user/snmp_user_provider_defaults.rb
tests/beaker_tests/snmp_user/snmp_userlib.rb

This PR is the puppet side of https://github.com/cisco/cisco-network-node-utils/pull/459
This simply reverses the changes from: https://github.com/cisco/cisco-network-puppet-module/pull/353
Tested on: n9k, n3k
```
|   `-- runBeakerTests                                                    PASSED
|       |-- Step 1: Beaker: Create Beaker Host Config                     PASSED
|       `-- Step 2: Beaker: Run Tests                                     PASSED
|-- beaker_native_results[suite=./snmp_user/snmp_user_provider_defaults.rb]    PASSED
|   `-- report                                                            PASSED
```

Remove broken snmp_user XR support

---

tests/beaker_tests/cisco_vlan/test_vlan.rb
tests/beaker_tests/lib/utilitylib.rb

* `feature vn-segment-vlan-based` is not supported on some n3k's
* Added a simple helper method to test for h/w support; the result is then used by `unsupported_properties` to update the test cases
* Tested on n3k(3048), n7k, n9k

Add agent_probe to utility.lib

---

tests/beaker_tests/cisco_interface/test_interface_capabilities.rb
tests/beaker_tests/lib/utilitylib.rb

* For some 3k, need to munge 'half/full' into csv-style 'half,full' to play nice with interface_capabilities
* This fix is a little trickier than the NU fix because the output from puppet resource is 'raw' whereas the NU output is a pre-processed hash of capabilities; thus we have to be careful not to munge the vsh or puppet resource output.
* Tested on n3048

Fix half/full in test_duplex

---

tests/beaker_tests/file_service_package/filesvcpkglib.rb
tests/beaker_tests/file_service_package/service_provider_nondefaults.rb
tests/beaker_tests/lib/utilitylib.rb

Our service provider beaker test was passing in native but failing in guestshell because the `bootlogd` service is only available in native.  With this update the test case now selects the service to test based on the OS family.
Tested on: n3k(native, guestshell), n9k(native, guestshell)
Not supported on OAC.

Update service provider beaker test to work in guestshell

---

tests/beaker_tests/cisco_vrf/test_vrf.rb
tests/beaker_tests/lib/utilitylib.rb

* N7k setup/cleanup when missing F3 cards
* New `image?` method for checking image version pattern; used as test for unprops
* New `remove_all_vrfs` method that uses `test_get`/`test_set`; this is much faster than removing vrfs one at a time

f3 handling for test_vrf

---

tests/beaker_tests/file_service_package/test_package.rb
tests/beaker_tests/lib/utilitylib.rb

This update allows us to test yum patching in both native and guestshell.  The workflow is different since we cannot use the puppet resource command in the guestshell to query information about patches applied to the native bash environment.
Tested on: n9k(I2, I3, I4, I5)

Enable yum package testing in guestshell

---

tests/beaker_tests/cisco_interface_ospf/test_interface_ospf.rb

* A previous test cleanup removed 'router ospf Sample' from the harness dependencies; now the nightly if failing when it tries to configure an ospf config on an interface
* Although the router config is not necessary for the interface config, the failure occurs because the ospf process is still starting up (ospf startup is slow on 5k/6k/8k). The ospf provider already has a 'wait_for_process_initialized' method to handle this slow start, while the interface_ospf provider does not. This is only an issue during testing so I do not propose adding the wait_for method to interface_ospf.
* Tested on n5,n7,n9

test_interface_ospf: Fix process dependency

---

tests/beaker_tests/cisco_interface_ospf/test_interface_ospf.rb

This update adds calls to `config_system_default_switchport` and `config_system_default_switchport_shutdown?` to ensure the interface under test is setup as an L3 interface before the test starts.

Update test_harness_dependencies for test_interface_ospf.rb

---

CHANGELOG.md
README.md
examples/cisco/demo_bgp.pp
lib/puppet/provider/cisco_bgp/cisco.rb
lib/puppet/type/cisco_bgp.rb
tests/beaker_tests/cisco_bgp/test_bgp.rb

This PR is for fixing few issues with event history properties as their defaults and behaviors have changed in the latest platform code release. Also added two new properties to event_history (errors and objstore) to the bgp provider which are available in the latest platform release.

bgp event_history

---

tests/beaker_tests/cisco_vrf/test_vrf.rb

This PR is for fixing vrf beaker test as the vrf description cannot be reset to default due to a bug in older releases. The fix is to skip the property for older images.

fix vrf beaker

---

CHANGELOG.md
README.md
examples/cisco/demo_interface.pp
examples/cisco/demo_pim.pp
lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/provider/cisco_pim/cisco.rb
lib/puppet/type/cisco_interface.rb
lib/puppet/type/cisco_pim.rb
tests/beaker_tests/cisco_interface/test_interface_L3.rb
tests/beaker_tests/cisco_pim/test_pim.rb

This PR is for adding bfd property to cisco_pim and pim_bfd property to cisco_interface providers. All tests pass.

pim and interface bfd

---

lib/puppet/type/cisco_interface_hsrp_group.rb

Summary:
This update fixes the issue with the cisco_interface_hsrp_group provider described in cisco/cisco-network-puppet-module#415
As the name of the interface is case sensitive, it was causing idempotent issues. Fixed

fix the case sensitive issue for interface_hsrp_group

---

lib/puppet/type/cisco_dhcp_relay_global.rb
tests/beaker_tests/cisco_dhcp_relay_global/test_dhcp_relay_global.rb

This PR is for fixing backspace issue for dhcp ipv4_sub_option_circuit_id_string. The NU changes are opened in another PR.

fix backspace issue for dhcp

---

tests/beaker_tests/cisco_route_map/test_route_map.rb
tests/beaker_tests/lib/utilitylib.rb

This PR is for removing all route maps before/after the beaker tests so that no residual configuration is left on the system

remove all route maps after beaker test

---

README.md

Previously the README was a mix of utf-8 symbols and GitHub emoji.  This was not properly rendering on Puppet Forge, as GitHub emoji codes are not supported.

Replace heavy_minus_sign emoji with utf-8 ➖symbol in README

---

lib/puppet/provider/package/cisco.rb

This PR is for fixing the package provider. The changes are for calling the Yum remove using the resource name for all cisco provider cases. Beaker tests pass.

package provider fix

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/type/cisco_interface.rb
tests/beaker_tests/cisco_interface/test_interface_L2.rb

This PR for adding purge_config property to interface provider so that the physical interface can be put back into default state. All tests pass on n3k, n6k, n9k.
This update fixes the issue with the cisco_interface provider described in https://github.com/cisco/cisco-network-puppet-module/issues/424

purge_config add to interface

---

CHANGELOG.md
README.md
examples/cisco/demo_interface.pp
lib/puppet/provider/cisco_interface_channel_group/cisco.rb
lib/puppet/provider/port_channel/cisco.rb
lib/puppet/type/cisco_interface_channel_group.rb
tests/beaker_tests/cisco_interface_channel_group/test_interface_channel_group.rb
tests/beaker_tests/file_service_package/test_package_patch.rb
tests/beaker_tests/lib/utilitylib.rb

This PR is for adding channel_group_mode to interface_channel_group provider. The new property channel_group_mode is optional (to keep backward compatibility). 
This PR also contains skip code for patch beaker tests if the version is I2 or I3. 
All tests pass on all platforms.

Channel group mode addition

---

README.md
lib/puppet/type/cisco_vpc_domain.rb

This update removes range checking in the `cisco_vpc_domain` type and instead allows the cli to reject invalid ranges.
This resolves https://github.com/cisco/cisco-network-puppet-module/issues/446

Remove range checks

---

CHANGELOG.md
README.md
examples/cisco/demo_bgp.pp
lib/puppet/provider/cisco_bgp_af_aa/cisco.rb
lib/puppet/type/cisco_bgp_af_aa.rb
tests/beaker_tests/cisco_bgp_af_aa/test_bgp_af_aa.rb

This PR is for adding a new provider bgp address family aggregate address. All tests pass on all platforms.
This is for addressing the enhancement request https://github.com/cisco/cisco-network-puppet-module/issues/452

Bgp address family aggregate address

---

tests/beaker_tests/cisco_route_map/test_route_map.rb

Just like the minitest, the beaker tests for route map need to be updated for handling the unordered representation of match_src_proto in running config on I7 (n9k only).

Add separate test for match_src_proto

---

tests/beaker_tests/lib/utilitylib.rb

This PR address the line wrap change that is seen in Puppet5. Changes made will be tested to retain compatibility with the existing Puppet version
Test Results :
Puppet 5 - 102P / 2 F / 11 S / 2 E
Puppet (current version) - 102/ 3F / 11S / 1E
2 of the failure are similar and needs to be investigated separately. The vrf testcases that errored out need to be investigated separately and they are not related to this diff.

Puppet5 test fix

---

tests/beaker_tests/cisco_command_config/test_command_config.rb
tests/beaker_tests/lib/utilitylib.rb

Made fixes to issues seen in puppet5. Errors seen in the tests were because `remove_all_vrfs` was silently failing to do it's job. Should now be fixed. 
All failed/errored tests were retested with puppet5 and latest puppet and are passing.

Puppet5 fixes

---

lib/puppet/provider/cisco_snmp_user/cisco.rb
lib/puppet/provider/snmp_user/cisco.rb
lib/puppet/type/cisco_aaa_authorization_login_cfg_svc.rb
lib/puppet/type/cisco_aaa_authorization_login_exec_svc.rb
lib/puppet/type/cisco_ace.rb

This PR is for fixing 3 customer reported issues:
1. snmp user throws error that user "admin" cannot be deleted
2. aaa_authorization_login_cfg_svc and aaa_authorization_login_exec_svc are not idempotent for groups property.
3. snmp_user 'admin' edge case

Fix for CISCO-50, CISCO-51, CISCO-52

---

tests/beaker_tests/lib/utilitylib.rb

**This PR addresses two issues:**
* Refactor the `nexus_image` method to use the `full_version` key.  Previously the method used the file name which is error prone.  System image files can be named anything the user desires.
* Fixes a bug in the beaker line-wrap fix in the `remove_all_vrfs` method.
Beaker line-wrap fix details.
Failure before this fix:
```
137928:   Beaker::Host::CommandFailure: Host 'n9k-157.cisco.com' exited with 127 running:
137929:    source /etc/profile; sudo sh -c " ip netns exec management /opt/puppetlabs/bin/puppet resource cisco_command_config 'cc' test_set='no cisco_command_config { 'cc':
137930:     test_get => '
137931:   vrf context blue
```
Fix tested using both puppet and puppet5 rpms.
**UPDATE:** Reverted change to `remove_all_vrfs`.  After a bit more …

Fixes to support fretta F3 images.

---

README.md
lib/puppet/type/cisco_bridge_domain.rb
tests/beaker_tests/cisco_bridge_domain/test_bridge_domain.rb

This PR is for fixing bridge-domain name default action and also adding 'default' keyword to fabric_control and shutdown properties. This is missing in the current code.

bridge_domain fixes

---

README.md
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

This PR is for removing peer-list and ingress replication from n7k as they are not supported on that platform. Tests pass

remove peerlist and ingress replication for n7k

---

tests/beaker_tests/lib/utilitylib.rb

This PR refactors the `remove_all_vrfs` method to better handle the differences in output between legacy and puppet5.
Tested on:
1. n7k: oac (puppet and puppet5)
2. n9k: native, guestshell (puppet and puppet5)
3. n9k-f: guestshell (puppet and puppet5)

Refactor remove_all_vrfs for puppet legacy and puppet5

---

lib/facter/cisco.rb

This PR is for improving the facts performance by a little bit.
As the 'uptime' facter flushes the cache (as it should), it is moved to the end so that the other facts can use the cache before it is flushed.
Beaker tests are run on n3k, n7k and n9k and they pass except few tests which are unrelated to this change.

Improve Facter performance

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_interface/cisco.rb
tests/beaker_tests/cisco_interface/test_interface_L2.rb
tests/beaker_tests/cisco_interface/test_interface_L3.rb
tests/beaker_tests/cisco_interface/test_interface_capabilities.rb
tests/beaker_tests/cisco_interface/test_interface_private_vlan.rb
tests/beaker_tests/cisco_interface/test_interface_stp.rb
tests/beaker_tests/cisco_interface/test_interface_svi.rb
tests/beaker_tests/lib/utilitylib.rb

This is the puppet side of https://github.com/cisco/cisco-network-node-utils/pull/562.  This update allows us to manage physical interfaces as `ensurable` resources.
**ensure => 'present'**
* Non-Physical Interfaces (vlans, loopbacks, port-channels, sub-interfaces)
* Created if absent
* Manage properties if present.
* Physical Interfaces (Ethernet)
* Default state: Creates a logical object to manage the interface and sets properties as needed.  Description property is automatically set to 'Managed by Puppet'
* Non-Default state: Manage properties.
**ensure => 'absent'**
* Non-Physical Interfaces (vlans, loopbacks, port-channels, sub-interfaces)
* Removed if present
* No action if absent
* Physical Interfaces (Ethernet)
* Issues the `default interface <int>` command if they are in a …

ensure => absent for physical cisco_interface provider

---

lib/puppet/provider/cisco_route_map/cisco.rb
lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/lib/utilitylib.rb

This PR is for using full_version facter instead of system_image. The latter uses bin file name which could be anything and so prone to errors.
All tests pass on n9k-f platform where the problem is seen.

fix system_image calls

---

CHANGELOG.md
lib/puppet/provider/radius_global/cisco.rb
lib/puppet/provider/syslog_server/cisco.rb
lib/puppet/provider/syslog_settings/cisco.rb
lib/puppet/provider/tacacs_global/cisco.rb
metadata.json
tests/beaker_tests/lib/utilitylib.rb
tests/beaker_tests/radius_global/radius_global_provider_defaults.rb
tests/beaker_tests/radius_global/radius_global_provider_nondefaults.rb
tests/beaker_tests/radius_global/radius_globallib.rb
tests/beaker_tests/syslog_server/syslog_server_provider_defaults.rb
tests/beaker_tests/syslog_server/syslog_serverlib.rb
tests/beaker_tests/syslog_settings/syslog_settings_provider_nondefaults.rb
tests/beaker_tests/syslog_settings/syslog_settingslib.rb
tests/beaker_tests/tacacs_global/tacacs_global_provider_defaults.rb
tests/beaker_tests/tacacs_global/tacacs_global_provider_nondefaults.rb
tests/beaker_tests/tacacs_global/tacacs_globallib.rb

This PR enhances the existing syslog, tacacs, and radius types as specified in  puppetlabs/netdev_stdlib#25
syslog_server
- port
syslog_settings
- console
- monitor
- source_interface
- vrf
tacacs_global
- source_interface
radius_global
- source_interface

(NETDEV-30) Enhance syslog, tacacs, radius

---

.gitignore
Gemfile
Rakefile

This commit updates the Gemfile to include puppet-blacksmith and updates the
Rakefile to include requiring the rake tasks for both puppet_spec_helper and
puppet-blacksmith.
This will allow use of rake tasks from both projects useful in testing and
publishing this module

Add puppet-blacksmith puppet_spec_helper gems/rake tasks

---

lib/puppet/provider/package/cisco.rb

With a master connected to AIX 6.1 and 7.1 and this module (and pre-reqs) installed, the following error would show on a puppet run of the aix agents:
`Info: Loading facts
Error: Could not autoload puppet/provider/package/cisco: Command yum is missing
Error: Facter: error while resolving custom facts in /opt/puppetlabs/puppet/cache/lib/facter/package_provider.rb: Could not autoload puppet/provider/package/cisco: Command yum is missing
Info: Caching catalog for aix-61-agent1.delivery.puppetlabs.net
Info: Applying configuration version '1510330826'`
Reviewing the provider for packages, an update to the rescue block makes sense to check for command missing, as that is the expected behavior on some other operating systems. 
Tested on 2017.3.2 master, agents 5.3.3
installed modules: …

Restrict package provider tests

---

Gemfile

This commit does two things:
1. Adds the beaker-abs gem in to the gemfile (this gem is another required gem
for working in the test environment at Puppet.)
2. Adds a puppet_test_env group to the gemfile, to allow users at puppet to
test with the beaker-abs gem and the users at cisco to install gems without it
if necessary.

Add requirement for beaker-abs in Gemfile, add puppet_test_env group

---

tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

Fixes the test to use the correct and supported option.

Use correct host_reachability flood for vxlan_vtp_vni dependencies

---

README.md

This update adds documentation for running puppet on Nexus with a user other then `admin`.

Admin cookie override

---

README.md
lib/puppet/provider/tacacs_global/cisco.rb
tests/beaker_tests/tacacs_global/tacacs_global_provider_defaults.rb

This commit changes the output of timeout from -1 to undef when not set.  This more accurately reflects the real world state of the resource.  Also allows users to set undef in their manifest to accept default value when configured.

(CISCO-60) tacacs_global timeout undef

---

tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb

Setting the `host_reachability` in the dependency manifest call impacts tests since some versions of Nexus require it to be set properly for ingress_replication.  We let the setter for ingress replication set the value properly.
Tests pass on N9k (h_dev, greensboro) and N7k.

Remove host_reachability from dependency_manifest call

---

CHANGELOG.md
lib/puppet/provider/network_trunk/cisco.rb
lib/puppet/provider/network_vlan/cisco.rb
lib/puppet/provider/port_channel/cisco.rb

The following providers were missing their confine.  This module supports netdev_stdlib and has to play nice with other providers.
A confine helps ensure this module does not interfere with other providers.
* network_trunk
* network_vlan
* port_channel

(CISCO-66) add missing confine to netdev_stdlib providers

---

CHANGELOG.md
docs/README-agent-install.md

**Summary:**
This PR updates documentation for the following:
* Indicate that puppet agent installs into the `bash-shell `are no longer supported.
* Add n3k low footprint workflow when using `guestshell`

Nexus release 9.2 documentation updates.

---

tests/beaker_tests/cisco_ip_multicast/test_ip_multicast.rb

The default value for overlay_spt_only flipped between I7.3 and I7.4
This commit addresses this behavior, which was already fixed in node_utils cisco/cisco-network-node-utils#582

(maint) fix cisco_ip_multicast test defaults

---

lib/puppet/provider/cisco_tacacs_server/cisco.rb
lib/puppet/provider/cisco_tacacs_server_host/cisco.rb
lib/puppet/type/cisco_tacacs_server.rb
lib/puppet/type/cisco_tacacs_server_host.rb
lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/cisco_tacacs_server/tacacsserver_provider_negatives.rb
tests/beaker_tests/cisco_tacacs_server/tacacsserver_provider_nondefaults.rb
tests/beaker_tests/cisco_tacacs_server/tacacsserverlib.rb

This PR fixes issue (https://tickets.puppetlabs.com/browse/CISCO-67)
If tacacs_server ```encryption_password``` is provided but not ```encryption_type```, it should be error out. 
Add check to see if the type is ```nil``` or ```none``` and throw error if password is present is the manifest.

Fix CISCO-67

---

tests/beaker_tests/file_service_package/test_service.rb
tests/beaker_tests/lib/utilitylib.rb

Currently we do not make any attempt to auto detect the system manager that is running inside of the various hosting environments on NXOS.  This PR attempts to address this problem.
1. Native bash-shell (init)
2. Guest-shell (systemd)
3. OAC (redhat)
Need to sort through the details of https://github.com/cisco/cisco-network-puppet-module/pull/493 before merging this PR.

Fix service test

---

tests/beaker_tests/file_service_package/test_package.rb

We have seen transient failures with these tests in CI
Set order of resources to ensure things are done in the correct order
```
Error: /Stage[main]/Main/Node[default]/Package[demo-one]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list demo-one' returned 1: Error: No matching Packages to list
```

(maint) update test_package ordering

---

README.md
lib/puppet/provider/network_interface/cisco.rb
lib/puppet/type/cisco_interface.rb

This PR is for fixing 
https://github.com/cisco/cisco-network-puppet-module/issues/497
The wrong speed problem exists in the network_interface as well. It is corrected too,

fix for issue cisco #497

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/type/cisco_interface.rb
tests/beaker_tests/cisco_interface/test_interface_L3.rb

Adds support to `cisco_interface` for `ipv6_redirects` attribute.
NodeUtils Changes: https://github.com/cisco/cisco-network-node-utils/pull/592

CISCO-77: cisco_interface add ipv6_redirects attribute

---

.travis.yml
Gemfile

The 0.2.0 release of net-telnet requires ruby >= 2.3.  We need to test ruby 1.9.3 until 31-Dec-18
Also bumped the travis rvm versions to match what is currently supported in puppet-agent.
@mikewiebe @willmeek this should resolve the travis issues that have popped up.

(maint) pin net-telnet version

---

CHANGELOG.md
lib/puppet/provider/cisco_interface_hsrp_group/cisco.rb
lib/puppet/type/cisco_interface_hsrp_group.rb
tests/beaker_tests/cisco_hsrp/test_interface_hsrp_group.rb

Removed default values for authentication. There are not defaults that are sane in this context. Users should supply explicit values.
Fixed authentication and ipv4/ipv6 validation
Requires cisco/cisco-network-node-utils#589

(CISCO-75/76) Fix cisco_interface_hsrp_group

---

CHANGELOG.md
lib/puppet/provider/package/cisco.rb

Facter was updated to identify guestshell as nexus - confine the operating system so we do not try to inspect with cisco provider on Puppet Device Nodes
Also cleaned up error from package inspector poking around vs managing resources

(CISCO-63) Confine package provider and fix inspector

---

CHANGELOG.md
README.md
lib/puppet/provider/cisco_ace/cisco.rb
lib/puppet/type/cisco_ace.rb
tests/beaker_tests/cisco_acl/test_ace.rb

This PR is for fixing issue cisco-73
https://tickets.puppetlabs.com/browse/CISCO-73
Tested on n7k, n3k and n9k.
For this config suggested in the bug:
```
ip access-list test-icp
10 permit icmp any any echo dscp af11
20 permit icmp any any precedence critical fragments
30 permit icmp any any dscp af12
```
Here is the puppet resource output:
```
cisco_ace { 'ipv4 test-icp 10':            
ensure       => 'present',               
action       => 'permit',                
dscp         => 'af11',                  
dst_addr     => 'any',                   
established  => 'false',                 
log          => 'false',                 
proto        => 'icmp',
proto_option => 'echo',
src_addr     => 'any',
}
cisco_ace { 'ipv4 test-icp 20':
ensure       => 'present',
action       => 'permit', …
```

Fix for Cisco-73

---

tests/beaker_tests/cisco_route_map/test_route_map.rb
tests/beaker_tests/cisco_upgrade/test_upgrade_idempotence.rb

Fixes the test_route_map ordering issue on 9k.

fix test_route_map beaker test for I9

---

CHANGELOG.md
README.md
lib/puppet/provider/syslog_settings/cisco.rb
tests/beaker_tests/syslog_settings/syslog_settings_provider_nondefaults.rb
tests/beaker_tests/syslog_settings/syslog_settingslib.rb

This commit adds the logfile_name, logfile_severity_level and logfile_size fields to syslog_settings for Cisco Nexus

(NETDEV-46) Add logfile to syslog_settings

---

CHANGELOG.md
lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/type/cisco_interface.rb
tests/beaker_tests/cisco_hsrp/test_interface_hsrp.rb
tests/beaker_tests/cisco_interface/test_interface_L2.rb
tests/beaker_tests/cisco_interface/test_interface_L3.rb
tests/beaker_tests/cisco_interface/test_interface_stp.rb

Fixes problem where cisco_interface returns illegal default values
Node Utils PR: https://github.com/cisco/cisco-network-node-utils/pull/595
**Tests:**
Puppet Manifest:
```puppet
node default {
cisco_interface { 'vlan13':
ensure => present,
}
}
```
```puppet
[root@guestshell ~]# puppet resource cisco_interface 'vlan13'
cisco_interface { 'vlan13':
ensure => 'absent',
}
[root@guestshell ~]# 
```
```puppet
[root@guestshell ~]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for n9k.example.com
Info: Applying configuration version '1536270600'
Notice: /Stage[main]/Main/Node[default]/Cisco_interface[vlan13]/ensure: created
Notice: Applied catalog in 13.29 seconds
[root@guestshell ~]# …
```

CISCO-74 Fix puppet resource interface defaults

---

CHANGELOG.md
README.md
lib/puppet/provider/banner/cisco.rb
tests/beaker_tests/banner/test_banner.rb

This commit adds the provider for the new banner type (netdev_stdlib)
Currently the only banner supported is MOTD.
Provider supports multiline banners with the following caveats
* module will attempt to escape any non-literal newlines
* NXAPI does not correctly set newlines in versions prior to 7.0(3)I7.4 / 9.2(1)
Requires cisco/cisco-network-node-utils#586 
Requires netdev_stdlib 0.15.1 (unreleased)

(CISCO-71) Add banner provider

---

README.md
examples/cisco/demo_acl.pp
examples/cisco/demo_vtp.pp
examples/cisco/demo_vxlan.pp
lib/puppet/parser/functions/platform_fretta.rb
lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/cisco_acl/test_acl.rb
tests/beaker_tests/cisco_evpn_multicast/test_evpn_multicast.rb
tests/beaker_tests/cisco_ip_multicast/test_ip_multicast.rb
tests/beaker_tests/cisco_vtp/vtp_provider_defaults.rb
tests/beaker_tests/cisco_vtp/vtp_provider_negatives.rb
tests/beaker_tests/cisco_vtp/vtp_provider_nondefaults.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
tests/beaker_tests/lib/utilitylib.rb

* This PR is for fixing beaker tests and software versioning scheme which changed from older versions to latest versions on n3k-f and n9k-f.
* Some of the features like vtp, acl, vxlan_vtp_vni etc. have a different behavior for these platforms and this is addressed.
All tests pass on n9k, n9k-f, n3k-f

Fixes for n9k-f and n3k-f

---

README.md

This PR is for fixing a documentation error. 
The ```timer_bgp_holdtime``` is mentioned in the README file as ```timer_bgp_hold```. This is corrected.
Also the interface name should not have white space is mentioned.

bgp timer name correction

---

tests/beaker_tests/cisco_route_map/test_route_map.rb

This PR is for fixing PUPPET JIRA Issue: https://tickets.puppetlabs.com/browse/CISCO-80.
Only the beaker test is the issue here and it is fixed by sorting the input.
Tested on different platforms and different versions.

Fix beaker test for route map src proto sort

---

.travis.yml
CHANGELOG.md
README.md
examples/cisco/demo_ospf.pp
lib/puppet/provider/cisco_ospf_vrf/cisco.rb
lib/puppet/type/cisco_ospf_vrf.rb
tests/beaker_tests/cisco_ospf_vrf/test_ospf_vrf.rb

This adds `redistribute` (from source protocol) support to router ospf via the `cisco_ospf_vrf` type/provider.
Note: route-maps are not optional with router ospf (redistribute from source protocol)
Note: `redistribute maximum-prefix` is not currently supported.
Travis bundler issue:  https://docs.travis-ci.com/user/languages/ruby/#bundler-20
runci test results: http://earms-trade.cisco.com/tradeui/resultsviewer.faces?ats=/auto/rtp-core/ats_shared/users/cvanheuv&client=web&host=rtp-ads-359&archive=/auto/rtp-core/ats_shared/users/cvanheuv/users/cvanheuv/archive/19-01/agents_job.2019Jan07_08:45:47.328021.zip
Resolves https://github.com/cisco/cisco-network-puppet-module/issues/531

Add 'redistribute' attribute to cisco_ospf_vrf provider

---

tests/beaker_tests/lib/utilitylib.rb

Logs important info on failure.
Now we get something like this:
```
* TestStep :: 1.1 Create Radius Server Manifest Present :: IDEMPOTENCE 
test_idempotence :: BEGIN
Idempotence Command: bundle exec puppet device --verbose --trace --strict=error --modulepath spec/fixtures/modules --deviceconfig /tmp/acceptance-device20190207-30317-d6q6kl.conf --target sut --libdir lib/  --apply /tmp/temp_test_apply20190207-30317-1bifdkw
Command Result: Notice: Compiled catalog for sut in environment production in 0.17 seconds
Info: Applying configuration version '1549572024'
Notice: /Stage[main]/Main/Radius_server[8.8.8.8]/key: key changed '\'44444444\'' to '44444444'
Notice: radius_server[8.8.8.8]: Updating: Updating '8.8.8.8' with {:name=>"8.8.8.8", :ensure=>"present", :auth_port=>77, :acct_port=>66, …
```

More idempotence logging please

---

lib/puppet/util/network_device/cisco_nexus/device.rb
tests/beaker_tests/cisco_ospf_vrf/test_ospf_vrf.rb

Refer to https://github.com/cisco/cisco-network-node-utils/pull/601#issuecomment-440338013 for the explanation. This basically allows for multiple devices to be managed in the same catalog compilation without environmental bleeding.

(maint) clearing down the node environment on new device instances

---

tests/beaker_tests/syslog_settings/test_syslog_settings.rb

Test was failing because it was looking for `-1` in the resource output instead of `unset`.  Updated the test to use `unset` because that is the documented method for unsetting the property.
https://github.com/puppetlabs/netdev_stdlib/blob/master/lib/puppet/type/syslog_settings.rb#L99

Update beaker to use unset for property

---

tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
tests/beaker_tests/lib/utilitylib.rb

* We had a 5/6k check for feature nv overlay in the test_harness_dependencies
section but that meant the test had to check and fail this check for every
single test case. My change just skips the entire test if the dependency is
not met.

beaker:vxlan deps: skip all tests if no nv overlay support on platform

---

tests/beaker_tests/cisco_vlan/test_vlan.rb
tests/beaker_tests/cisco_vrf/test_vrf.rb
tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb
tests/beaker_tests/lib/utilitylib.rb

Mostly n6k test errors. Also noticed that `test_vrf` was not raising an error in `test_manifest` when it hit the `NVE Feature NOT supported on this Platform` failure, which passed because the `'Applied catalog'` string shows up in the output. The code logic also needs to know how to handle intended errors (negative testing) so my change is to explicitly look for `Error: ` in the output but only when the caller does not supply a `stderr_pattern`.
Tested with agentless on N6k; will update after testing with agentful.

beaker: Add NVE probes to vrf/vlan tests; test_manifest hidden errors

---

lib/puppet/functions/find_linecard.rb
lib/puppet/functions/image_supports_trm.rb
lib/puppet/functions/platform_fretta.rb
lib/puppet/functions/platform_get.rb

These requires were missed during a conversion and would lead to the following errors:
```
Error while evaluating a Function Call, uninitialized constant Puppet::Util::NetworkDevice
```

(maint) adding in the requires for the puppet functions

---

docs/README-agent-install.md

This commit adds a note to the README about the agent being phased out after 2018.1. 
https://tickets.puppetlabs.com/browse/DOC-3953

(DOC-3953) README update for 2.0 release

---

tests/beaker_tests/lib/utilitylib.rb

Printing the output on test failures helps debugging them through allowing
inspection of the failure from CI logs.

(maint) add more debugging to test_stderr

---

lib/puppet/transport/schema/cisco_nexus.rb
metadata.json
tests/beaker_presuite/presuite_deploy.rb
tests/beaker_tests/lib/utilitylib.rb

Transport schema Port should be an Integer rather than a String.
The metadata refers to the Resource API gem rather than module and so minimum should be the 1.0.0 release

(maint) Minor fixes

---

.sync.yml
Rakefile

PDK sync.yml updates the Rakefile to add an extra non-guarded puppet-strings/tasks.
Remove this.

(maint) Remove extra require from Rakefile

---

lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/provider/cisco_interface_ospf/cisco.rb
tests/beaker_tests/cisco_interface/test_interface_threshold.rb
tests/beaker_tests/lib/utilitylib.rb

- This is part 2 of the interface performance work started by #561.
- This commit builds on the perf work done for that PR.
- NU dependencies have already been merged.
- https://github.com/cisco/cisco-network-node-utils/pull/637
- Beaker test `test_interface_threshold.rb` was updated to also test interface_ospf. Additional tests will be added for the other intf providers as the code is completed.
- Tested on dt-n9k5-1

cisco_interface_ospf: interface lookup performance enhancement

---

lib/puppet/provider/cisco_interface_channel_group/cisco.rb
lib/puppet/provider/cisco_interface_evpn_multisite/cisco.rb
tests/beaker_tests/cisco_interface/test_interface_threshold.rb

- This is part 3 of the interface performance work started by #561.
- This commit builds on the perf work done for that PR.
- NU dependencies have already been merged.
- https://github.com/cisco/cisco-network-node-utils/pull/632
- Beaker test `test_interface_threshold.rb` was updated to also test these changes. 
- Tested on dt-n9k5-1 and n9k-140

cisco_interface_: channel_group, evpn_multisite interface perf fixes

---

tests/beaker_tests/lib/utilitylib.rb

We only support `vdc` on `N7` platforms. 
This check was failing because `show vdc` cli is not present on some platforms.

skip_non_default_vdc: vdc is only supported on 7k platforms

---

lib/puppet/provider/cisco_interface/cisco.rb
lib/puppet/provider/cisco_interface_channel_group/cisco.rb
lib/puppet/provider/cisco_interface_evpn_multisite/cisco.rb
lib/puppet/provider/cisco_interface_ospf/cisco.rb
tests/beaker_tests/cisco_acl/test_ace.rb

This change allows the new puppet module to work with an older NU gem. 
Manually tested on n9k-108.

Add NU gem version checks to allow backward-compatibility

---

tests/beaker_tests/lib/utilitylib.rb

Display the following in beaker agentless run logs.
* Contents of the manifest data being applied
* Command used to apply the manifest in agentless mode.
* Output from applying the manifest.
**Sample output:**
```
* TestStep :: 2.1 Common Non Defaults [ensure => present] :: MANIFEST    
test_manifest :: manifest:
0
test_manifest :: check puppet apply cmd (code: [2])
test_manifest :: manifest contents :: 
cisco_itd_service { 'myService':
ensure => present,
access_list                              => 'iap',
device_group                             => 'udpGroup',
exclude_access_list                      => 'eap',
fail_action                              => 'true',
ingress_interface                        => [["vlan 2", "4.4.4.4"], ["ethernet 1/10", "5.5.5.5"], ["port-channel 100", …
```

Make agentless beaker easier to debug

---

tests/beaker_tests/cisco_ip_multicast/test_ip_multicast.rb

This test only runs on n9k.  The failure in the beaker test indicated that the nve interface needed to be in the shutdown state before the multicast `overlay_distributed_dr`  property in question could be set.
This test does not validate nve but it should cleanup any nve interfaces as part of the setup step.  Currently only one nve interface can be configured.
Tested on N9k (GS and agentless)

Add cleaup nve interface for ip_multicast test

---

lib/puppet_x/cisco/cmnutils.rb
tests/beaker_tests/lib/utilitylib.rb

- Small refactor to make the `facts_ref` lookup reusable.
- The idempotency check was only checking for positive conditions and ignoring Error states.

cmnutils refactor, utilitylib better idempotency check

---

tests/beaker_tests/cisco_itd_service/test_itd_service.rb

The next-hop setting as part of the ingress_interface is not needed for n9k and in the latest images is not even supported by the cli.
Tested on n7k and n9k

Fix ITD next-hop test for 9.x image versions
