cisco/cisco-network-puppet-module

- CHANGELOG.md
- README.md
- docs/README-agent-install.md
- metadata.json
Just a doc update to reflect the new package filenames/urls.
> v1.0.2 release

- docs/README-develop-types-providers.md
- docs/template-type-feature.rb
- examples/README.md
Updates to puppet developer guide.
> Updated to clarify developer workflow

- README.md
- lib/puppet/provider/cisco_bgp_neighbor_af/nxapi.rb
- lib/puppet/type/cisco_bgp_neighbor_af.rb
- tests/beaker_tests/bgpneighboraf/test_bgpneighboraf.rb
route-map in/out have the same behaviors as filter-list in/out so this is just a copy/replace for the most part.
- rubocop'd
- beaker'd (tests added & run)
- Docs updated
> Added 'route-map' support to bgp_neighbor_af

- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp/nxapi.rb
- lib/puppet/type/cisco_bgp.rb
- tests/beaker_tests/bgp/bgplib.rb
- tests/beaker_tests/bgp/test_bgp_defaults.rb
- tests/beaker_tests/bgp/test_bgp_non_defaults.rb
- tests/beaker_tests/bgp/test_bgp_title_patterns.rb
pull again and add all the changes
> Add enforce-first-as to bgp

- docs/README-maintainers.md
Adding release checklist to the maintainers guide. Please take a look and let me know if I'm missing anything!
> Add release checklist

- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp_af/nxapi.rb
- lib/puppet/type/cisco_bgp_af.rb
- tests/beaker_tests/bgpaf/test_bgpaf.rb
1. pass beaker test
Please help me check the code
> add maximum-paths to bgp_af

- tests/beaker_tests/bgpneighbor/test_bgpneighbor_defaults.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_nondefaults.rb
1. pass the beaker test 
2. test the default value to false
> test ebgp multihop default as false

- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp_af/nxapi.rb
- lib/puppet/type/cisco_bgp_af.rb
- tests/beaker_tests/bgpaf/test_bgpaf.rb
> Add redistribute property to bgp_af

- CHANGELOG.md
- README.md
- metadata.json
Updates to add new cisco and netdev resources.
> README.md and CHANGELOG.md updates

- CHANGELOG.md
- README.md
- examples/demo_interface.pp
- lib/puppet/provider/cisco_interface/nxapi.rb
- lib/puppet/type/cisco_interface.rb
- tests/beaker_tests/routedintf/routedintf_provider_defaults.rb
- tests/beaker_tests/routedintf/routedintf_provider_nondefaults.rb
- tests/beaker_tests/routedintf/routedintflib.rb
this is waiting on https://github.com/cisco/cisco-network-node-utils/pull/47/files
> implementing speed and duplex with tests

- examples/demo_bgp.pp
- lib/puppet/type/cisco_bgp.rb
- lib/puppet/type/cisco_bgp_af.rb
- lib/puppet/type/cisco_bgp_neighbor.rb
- lib/puppet/type/cisco_bgp_neighbor_af.rb
This update addresses the following.
1) With our more complex title patterns, bgp resources were not idempotent.  This was fixed by overriding the name method to return the correct set of values matching the title.
2) Update to demo_bgp.pp to use complex title patterns for all examples and enable additional functionality.
> BGP Updates

- tests/beaker_tests/fileservicepkg/service_provider_nondefaults.rb
- tests/beaker_tests/network_snmp/network_snmp_provider_defaults.rb
- tests/beaker_tests/ntp_config/ntp_config_provider_defaults.rb
- tests/beaker_tests/ntp_server/ntp_server_provider_defaults.rb
- tests/beaker_tests/syslog_server/syslog_server_provider_defaults.rb
- tests/beaker_tests/syslog_settings/syslog_settings_provider_defaults.rb
Modified beaker file tests now pass.
> Beaker cleanup fixes

- tests/beaker_tests/netdev_stdlib/domain_name_provider_defaults.rb
> Beaker cleanup fix

- README.md
- examples/demo_netdev_tacacs_server_group.pp
- lib/puppet/provider/tacacs_server_group/nxapi.rb
- tests/beaker_tests/tacacs_server_group/tacacs_server_group_provider_defaults.rb
- tests/beaker_tests/tacacs_server_group/tacacs_server_grouplib.rb
Exactly the same as radius_server_group, which has been merged
> Added NXOS provider for tacacs_server_group

- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp_neighbor/nxapi.rb
- lib/puppet/type/cisco_bgp_neighbor.rb
- tests/beaker_tests/bgp/bgplib.rb
- tests/beaker_tests/bgpneighbor/bgpneighborlib.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_defaults.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_negative.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_nondefaults.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_password.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_titlepattern.rb
- tests/beaker_tests/bgpneighbor/test_bgpneighbor_transport_passive_mode.rb
- tests/beaker_tests/lib/utilitylib.rb
New PR to fix the commit history of the last one.  No changes since last review.
> BGP Neighbor puppet support for XR.

- CHANGELOG.md
- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp_af/nxapi.rb
- lib/puppet/type/cisco_bgp_af.rb
- tests/beaker_tests/bgpaf/test_bgpaf.rb
1. pass beaker test
Total Suite Time: 377.94 seconds
Average Test Time: 377.94 seconds
Attempted: 1
Passed: 1
Failed: 0
Errored: 0
Skipped: 0
Pending: 0
Total: 1
2. pass static analysis
> add to cisco_bgp_af

- CHANGELOG.md
- README.md
- examples/demo_interface.pp
- lib/puppet/provider/cisco_interface/nxapi.rb
- lib/puppet/type/cisco_interface.rb
- tests/beaker_tests/routedintf/routedintf_provider_negatives.rb
- tests/beaker_tests/routedintf/routedintf_provider_nondefaults.rb
- tests/beaker_tests/routedintf/routedintflib.rb
@saichint had most of this work already done and near approval but he was pulled
to help with test / bugfix efforts; I tried to merge this diff with the intent of
finishing it up with a separate PR but ran into issues with the merge. So instead
I closed #96 and I'm submitting the final fixes here.
> Resubmit channel-group changes for PR #96

- lib/puppet/type/cisco_vni.rb
Change from VXLAN Network Identifier to Virtual Network Identifier
> VNI = Virtual Network Identifier

- CHANGELOG.md
- lib/puppet/provider/cisco_evpn_vni/nxapi.rb
- lib/puppet/type/cisco_evpn_vni.rb
- tests/beaker_tests/cisco_evpn_vni/test_evpn_vni.rb
1. pass the beaker test
2. pass static analysis
> add cisco_evpn_vni

- CHANGELOG.md
- README.md
- examples/demo_netdev_snmp.pp
- lib/puppet/provider/snmp_notification_receiver/nxapi.rb
- tests/beaker_tests/snmp_notification_receiver/snmp_notification_receiver_provider_defaults.rb
- tests/beaker_tests/snmp_notification_receiver/snmp_notification_receiverlib.rb
Requires https://github.com/puppetlabs/netdev_stdlib/pull/17 to be merged first.
> Added NXOS provider for snmp_notification_receiver

- CHANGELOG.md
- README.md
- examples/demo_bgp.pp
- lib/puppet/provider/cisco_bgp/nxapi.rb
- lib/puppet/type/cisco_bgp.rb
- tests/beaker_tests/cisco_bgp/bgplib.rb
- tests/beaker_tests/cisco_bgp/test_bgp_defaults.rb
- tests/beaker_tests/cisco_bgp/test_bgp_non_defaults.rb
- tests/beaker_tests/cisco_bgp/test_bgp_title_patterns.rb
1. pass beaker test 
2. pass static analysis
> add disable_policy_batching to cisco_bgp

- CHANGELOG.md
- README.md
- examples/demo_interface.pp
- lib/puppet/provider/cisco_interface/nxapi.rb
- lib/puppet/type/cisco_interface.rb
- tests/beaker_tests/cisco_interface/routedintf_provider_negatives.rb
- tests/beaker_tests/cisco_interface/routedintf_provider_nondefaults.rb
- tests/beaker_tests/cisco_interface/routedintflib.rb
rubocop is good. Tested the provider code via example/demo manifests and results were good.
I couldn't run beaker tests because of some environmental issue. 
Wanted to raise a PR while waiting for help on getting the beaker testing done.
thanks
-Pradeep.
> acl interface provider/type

- examples/demo_vrf.pp
- lib/puppet/parser/functions/find_linecard.rb
- lib/puppet/parser/functions/prop_supported.rb
-Fix demo_vrf.pp to use these functions
> Add manifest functions: find_linecard, prop_supported

- examples/demo_bgp.pp
> add demo_bgp.pp

- tests/beaker_tests/radius_server_group/radius_server_group_provider_defaults.rb
- tests/beaker_tests/radius_server_group/radius_server_grouplib.rb
@jonnytpuppet Re-opening #153 for `release_1.2.0`
> Updated radius_server_group_tests for IPv6

- tests/beaker_tests/radius_server_group/radius_server_group_provider_defaults.rb
- tests/beaker_tests/radius_server_group/radius_server_grouplib.rb
Reverts cisco/cisco-network-puppet-module#164
> Revert "Updated radius_server_group_tests for IPv6"

- lib/puppet/provider/cisco_ace/nxapi.rb
- tests/beaker_tests/radius_server_group/radius_server_group_provider_defaults.rb
- tests/beaker_tests/radius_server_group/radius_server_grouplib.rb
@jonnytpuppet 2nd try at merging #153 into `release_1.2.0`
> Radius server group ipv6

- README.md
netdev changes will be in the next PR
> Rel 1.2.0 doc chgs cisco-only

- CHANGELOG.md
- README.md
- examples/cisco/demo_vxlan.pp
- lib/puppet/provider/cisco_vxlan_vtep/nxapi.rb
- lib/puppet/type/cisco_vxlan_vtep.rb
- tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
Committing on behalf of @alok-aggarwal. See PR #197.
> Add cisco_vxlan_vtep:source_interface_hold_down_time

- CHANGELOG.md
- README.md
- docs/README-agent-install.md
- metadata.json
- Download link for Nexus 5000 and Nexus 6000 Open Agent Container (OAC).
- OAC programmability guide links.
- Complete cisco_ace documentation.
> Hotfix 1.2.3 - Documentation Only

- README.md
- examples/cisco/demo_vrf.pp
- tests/beaker_tests/cisco_vrf/test_vrf.rb
- tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb
Rally story US63947 (TA88173, TA88174).
Both tests passed on nexus and xr.
> made the existing test_vrf, test_vrf_af working for both nexus and XR

- tests/beaker_tests/cisco_acl/test_ace.rb
- tests/beaker_tests/cisco_acl/test_acl.rb
- tests/beaker_tests/lib/utilitylib.rb
* Also added some missing properties to test_ace
> Refactor beaker test_acl to handle platform diffs

- CHANGELOG.md
- README.md
- examples/cisco/demo_vrf.pp
- lib/puppet/provider/cisco_vrf/cisco.rb
- lib/puppet/type/cisco_vrf.rb
- tests/beaker_tests/cisco_vrf/test_vrf.rb
All beaker tests passed on eXR and n9kv.
> US75672: add cisco_vrf:pt:new SILK1 attributes

- README.md
- examples/netdev/demo_radius.pp
- lib/puppet/provider/radius_server/cisco.rb
- tests/beaker_tests/radius_server/radius_server_provider_defaults.rb
- tests/beaker_tests/radius_server/radius_serverlib.rb
Needed for https://github.com/cisco/cisco-network-node-utils/pull/256 to work
> Updated radius_server for EXR support

- CHANGELOG.md
- README.md
- lib/puppet/provider/tacacs_server/cisco.rb
Needs https://github.com/cisco/cisco-network-node-utils/pull/307/files
> Added IOS XR support for tacacs_server

- README.md
* Doc-only changes. There was no documentation for evpn_vni prior to this change.
> Add evpn_vni text to readme

- README.md
- lib/puppet_x/cisco/autogen.rb
- tests/beaker_tests/cisco_vrf/test_vrf.rb
- tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb
> vrf: platform updates for beaker

- CHANGELOG.md
- README.md
This PR is for network_dns doc only. The changes are for adding support to all nexus platforms as the tests are all pass.
> network_dns documentation

- tests/beaker_tests/netdev_stdlib/network_trunk_provider_defaults.rb
- tests/beaker_tests/netdev_stdlib/network_trunklib.rb
* Replace hard-coded interface names with dynamic lookup
* Tested on n3,n6,n7,n9
> netdev:network_trunk: use find_interface

- tests/beaker_tests/cisco_itd_service/test_itd_service.rb
Small issue due to timing is fixed with this PR.
> Fix itd_service beaker

- tests/beaker_tests/netdev_stdlib/network_vlan_provider_nondefaults.rb
Added code to get rid of bridge domains so that the beaker tests pass
> netdev network_vlan

- tests/beaker_tests/cisco_bgp_neighbor_af/test_bgpneighboraf.rb
* dependency_manifest() included a route_distinguisher setup (required for XR)
* N3k-I2 images don't support rd
* Most of the dependencies are only req'd for XR so I rearranged the config setup limit the config to XR
* Tested on N3k-I2, N6k, N9k-I3
> test_bgp_neighbor_af: rd breaks I2 tests

- docs/README-agent-install.md
http://man7.org/linux/man-pages/man5/resolv.conf.5.html
> domain and search options are mutually exclusive

- docs/README-agent-install.md
- docs/README-beaker-prerequisites.md
- docs/README-gem-install.md
- docs/template-beaker-feature.rb
- docs/template-beaker-router.rb
Reverts cisco/cisco-network-puppet-module#304
> Revert "Remove XR  and N8K references from README docs."

- lib/puppet/provider/cisco_vxlan_vtep/cisco.rb
- tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
- tests/beaker_tests/lib/utilitylib.rb
* Tested on n3-i2,n5,n6,n7,n9-i2,n9-i3
> Convert test_vxlan_vtep to use new syntax

- docs/README-agent-install.md
> Release 1.3.0

- README.md
This PR is for documenting the pre-requisites for cisco_itd_service.
> Readme.md changes for itd_service

- tests/beaker_tests/cisco_overlay_global/test_overlay_global.rb
* DME changes for l2rib properties resulted in removal of the 'default' keyword from the cli:
`l2rib dup-host-mac-detection default`
* Prior to this change, 'default' was the only way to reset the host_moves & timeout properties back to default; there was/is no 'no' command, so the only way to reset it now is to re-enter the command with the default values.
* This change necessitates changes to the setter, minitest, and beaker. I also changed the default values to actual integer values instead of empty strings.
* Tested minitest & beaker for: n9-edev,n9-I4,n5,n6. Skips for n3 (normal) and n7 (requires F3 card).
> New overlay_global behaviors

- tests/beaker_tests/cisco_interface/test_interface_L3.rb
* ip pim sparse-mode was failing to nvgen during the test
* Factors: a) the intf is in vrf 'test1'; and, b) 'test1' has not been instantiated yet
* Normally these forward-references are not a problem but the new DME-based PIM cli is silently rejecting it because the vrf is not instantiated
* For puppet it's not unreasonable to require a pre-instantiated vrf, and since this change only affects our beaker test I'm just going to update the test. The PIM team did say they would reconsider raising an error for this, or better yet just create the pim cli object regardless of vrf-instantiation state.
* Also fixed a cleanup issue for dot1q sub-ints.
* Tested on N9-I5
> L3 PIM-on-VRF-intf beaker fix

- tests/beaker_tests/cisco_interface/test_interface_vlan_mapping.rb
- tests/beaker_tests/cisco_vlan/test_vlan.rb
- tests/beaker_tests/lib/utilitylib.rb
> Add f3 utility for n7 bkr tests

- lib/puppet/provider/cisco_command_config/cisco.rb
- tests/beaker_tests/cisco_command_config/test_command_config.rb
This PR resolves https://github.com/cisco/cisco-network-puppet-module/issues/417
**Tested on:** n3k, n7k, n9k
> Fix Chrun: console and vty config #417

- tests/beaker_tests/file_service_package/test_package_patch.rb
This PR is for fixing the beaker test for patch files. Expanded the test for evergreen1 and evergreen2 releases. Tested and result is pass
> fix beaker patch test for evergreen

- CHANGELOG.md
- README.md
- examples/cisco/demo_object_group.pp
- examples/demo_all_cisco.pp
- lib/puppet/provider/cisco_object_group/cisco.rb
- lib/puppet/provider/cisco_object_group_entry/cisco.rb
- lib/puppet/type/cisco_object_group.rb
- lib/puppet/type/cisco_object_group_entry.rb
- tests/beaker_tests/cisco_object_group/test_object_group.rb
This PR is for adding object_group and object_group_entry providers. 
All tests pass.
> Object_group

- README.md
This PR is for fixing the documentation for object_group provider
> fix readme for object_group

- CHANGELOG.md
- README.md
- examples/cisco/demo_trm.pp
- examples/demo_all_cisco.pp
- lib/puppet/parser/functions/image_supports_trm.rb
- lib/puppet/parser/functions/prop_supported.rb
- lib/puppet/provider/cisco_evpn_multicast/cisco.rb
- lib/puppet/provider/cisco_vrf_af/cisco.rb
- lib/puppet/type/cisco_evpn_multicast.rb
- lib/puppet/type/cisco_vrf_af.rb
- tests/beaker_tests/cisco_evpn_multicast/test_evpn_multicast.rb
- tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb
- added type, provider and beaker tests for evpn_multicast
- added type, provider and beaker tests for cisco_vrf_af modifications
> TRM (part 1)

- CHANGELOG.md
- lib/puppet/provider/syslog_server/cisco.rb
- metadata.json
- tests/beaker_tests/syslog_server/syslog_server_provider_defaults.rb
Customer request.  Requires release of netdev_stdlib and merging of cisco/cisco-network-node-utils#583
> (NETDEV-39) add facility to syslog_server

- CHANGELOG.md
- README.md
- lib/puppet/provider/network_dns/cisco.rb
This commit adds a hostname field to network_dns.
> (NETDEV-37) Add hostname to network_dns provider

- CHANGELOG.md
- README.md
- examples/cisco/demo_vxlan.pp
- lib/puppet/provider/cisco_vxlan_vtep/cisco.rb
- lib/puppet/provider/cisco_vxlan_vtep_vni/cisco.rb
- lib/puppet/type/cisco_vxlan_vtep.rb
- lib/puppet/type/cisco_vxlan_vtep_vni.rb
- tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
- tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
This PR is for adding new configurations for vxlan vtep and vxlan vtep vni.
Tests are run on relevant platforms and they are ok.
> Add new config for Vxlan Vtep

- README.md
This PR is for documentation as per the latest vxlan CLI changes.
> documentation changes for vxlan cli

- tests/beaker_tests/cisco_acl/test_ace.rb
This was originally coded with elsif's so the last set of attrs
was being ignored. I updated the logic to match our other tests.
> beaker:test_ace: fix unprops

- Gemfile
- README.md
- Rakefile
- docs/README-beaker-prerequisites.md
- docs/README-install_guide.md
- spec/fixtures/device.conf
**Summary:**
* Replace copyright statements that were inadvertently removed during the agentless work.
* Add more explicit guidelines to the main README for agent and agentless workflows.
* Fix broken links and update links to point to newer versions of the programmability guides.
> Puppet 2.0.0 Release Doc Updates

- tests/beaker_tests/cisco_vlan/test_vlan.rb
- tests/beaker_tests/lib/utilitylib.rb
> beaker:test_vlan: add a resource_probe check for n6k nv overlay

- tests/beaker_tests/cisco_snmp_community/test_snmp_community.rb
- tests/beaker_tests/cisco_tacacs_server/test_tacacs_server.rb
- tests/beaker_tests/cisco_tacacs_server_host/test_tacacs_server_host.rb
As highlighted by utilitylib fix
> (FM-7812) Fix negative tests

- tests/beaker_tests/cisco_snmp_community/test_snmp_community.rb
- tests/beaker_tests/cisco_tacacs_server/test_tacacs_server.rb
- tests/beaker_tests/cisco_tacacs_server_host/test_tacacs_server_host.rb
As highlighted by utilitylib fix
> Release 2.0.0 Fixes

- spec/unit/puppet/transport/cisco_nexus_spec.rb
- tests/beaker_tests/cisco_bridge_domain/test_bridge_domain_vni.rb
- tests/beaker_tests/cisco_encapsulation/test_encapsulation.rb
- tests/beaker_tests/cisco_fabricpath_global/test_fabricpath_global.rb
- tests/beaker_tests/cisco_fabricpath_topology/test_fabricpath_topology.rb
- tests/beaker_tests/cisco_interface/test_interface_vlan_mapping.rb
- tests/beaker_tests/cisco_overlay_global/test_overlay_global.rb
- tests/beaker_tests/cisco_vdc/test_vdc.rb
- tests/beaker_tests/cisco_vlan/test_vlan.rb
- tests/beaker_tests/cisco_vpc_domain/test_vpc_domain.rb
- tests/beaker_tests/cisco_vrf/test_vrf.rb
- tests/beaker_tests/cisco_vrf_af/test_vrf_af.rb
- tests/beaker_tests/cisco_vxlan_vtep/test_vxlan_vtep.rb
- tests/beaker_tests/cisco_vxlan_vtep_vni/test_vxlan_vtep_vni.rb
- tests/beaker_tests/lib/utilitylib.rb
- Test's that run the command `show run pdk` now skipped
> (FM-8271) - Exceptions added to the code for Non-Default VDC's

- tests/beaker_tests/cisco_acl/test_ace.rb
> test_ace: ttl /10/3/

- lib/facter/cisco_nexus.rb
- lib/puppet/provider/cisco_interface/cisco.rb
- lib/puppet/provider/cisco_interface_channel_group/cisco.rb
- lib/puppet/provider/cisco_interface_evpn_multisite/cisco.rb
- lib/puppet/provider/cisco_interface_ospf/cisco.rb
- lib/puppet_x/cisco/cmnutils.rb
- spec/unit/puppet/transport/cisco_nexus_spec.rb
- tests/beaker_tests/cisco_interface/test_interface_threshold.rb
Tested on n9k-108/GS and n6k-77/Agtless.
> Move threshold logic into cmnutils
